### PR TITLE
Fix #428 PHP 5.1.6 unexpected '['

### LINKED ISSUE #428: Meterpreter running in PHP 5.1.6 dies after startup (unexpected '[')
Meterpreter running in PHP 5.1.6 dies immediately after startup in a similar fashion to #95 

```
$ php pwn.php 
/*PHP Parse error:  syntax error, unexpected '[' in <REDACTED>/pwn.php(1) : eval()'d code on line 515
```

The code that triggers this is:

```php
$id_start = packet_get_tlv($req, TLV_TYPE_UINT)['value'];
$id_end = packet_get_tlv($req, TLV_TYPE_LENGTH)['value'] + id_start;
```

This is the same style of code "fixed" in #95 

(╯°□°)╯︵PHP

PR incoming

### PR DESCRIPTION
**Pull request by justinsteven**

### CODE REVIEW

File: php/meterpreter/meterpreter.php [hunk 1]
```diff
@@ -512,8 +512,10 @@ function core_enumextcmd($req, &$pkt) {
 
     global $id2f;
 
-    $id_start = packet_get_tlv($req, TLV_TYPE_UINT)['value'];
-    $id_end = packet_get_tlv($req, TLV_TYPE_LENGTH)['value'] + id_start;
+    $id_start_array = packet_get_tlv($req, TLV_TYPE_UINT);
+    $id_start = $id_start_array['value'];
+    $id_end_array = packet_get_tlv($req, TLV_TYPE_LENGTH);
+    $id_end = $id_end_array['value'] + id_start;
```
Comment (justinsteven) [inline php/meterpreter/meterpreter.php:518]: I noticed while submitting this patch that `id_start` doesn't have a `$` stuck on the front. Is this a typo? Or some PHP magic? Worth fixing?

Comment (bcoles) [reply php/meterpreter/meterpreter.php:518]: Looks like a bug at first glance

**Comment by justinsteven** [comment]
Fixes #428

File: php/meterpreter/meterpreter.php (hunk 1 above)
Comment (bcoles) [reply php/meterpreter/meterpreter.php:518]: Presumably it is intentionally arithmetic rather than concatenation.

A few tests on PHP 7:

```
# php --version
PHP 7.4.5 (cli) (built: Jun  3 2020 20:55:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.5, Copyright (c), by Zend Technologies

# php -r '$asdf = 123; echo "hello" + asdf;'
PHP Warning:  Use of undefined constant asdf - assumed 'asdf' (this will throw an Error in a future version of PHP) in Command line code on line 1
PHP Warning:  A non-numeric value encountered in Command line code on line 1
PHP Warning:  A non-numeric value encountered in Command line code on line 1
0

# php -r '$asdf = "123"; echo "hello" + asdf;'
PHP Warning:  Use of undefined constant asdf - assumed 'asdf' (this will throw an Error in a future version of PHP) in Command line code on line 1
PHP Warning:  A non-numeric value encountered in Command line code on line 1
PHP Warning:  A non-numeric value encountered in Command line code on line 1
0

# php -r '$asdf = 123; echo "hello" + $asdf;'
PHP Warning:  A non-numeric value encountered in Command line code on line 1
123

# php -r '$asdf = "123"; echo "hello" + $asdf;'
PHP Warning:  A non-numeric value encountered in Command line code on line 1
123

# php -r '$asdf = 123; echo 999 + $asdf;'
1122

# php -r '$asdf = 123; echo 999 + asdf;'
PHP Warning:  Use of undefined constant asdf - assumed 'asdf' (this will throw an Error in a future version of PHP) in Command line code on line 1
PHP Warning:  A non-numeric value encountered in Command line code on line 1
999
```

Comment (justinsteven) [reply php/meterpreter/meterpreter.php:518]: Hmm

If I add to Meterpreter:

```php
echo "\n";
echo gettype($id_start) . ": $id_start\n";
echo gettype($id_end) . ": $id_end\n";

```

Then without the `$` in front of `id_start` I get:

```
$ php pwn.php 
/*
integer: 1000
integer: 1000
```

With `$id_start` I get:

```
$ php pwn.php 
/*
integer: 1000
integer: 2000
```

Looking at fc0079e98 (especially the Python code) it looks like the intention was the latter.

But the Python code seems to have its own error (`start` should be `id_start`, right?)

Comment (justinsteven) [reply php/meterpreter/meterpreter.php:518]: OJ confirmed the missing `$` was a typo. I'll fix.

Comment (bcoles) [reply php/meterpreter/meterpreter.php:518]: > Then without the `$` in front of `id_start` I get:
> 
> ```
> $ php pwn.php 
> /*
> integer: 1000
> integer: 1000
> ```
> 
> With `$id_start` I get:
> 
> ```
> $ php pwn.php 
> /*
> integer: 1000
> integer: 2000
> ```
> 
> Looking at [fc0079e](https://github.com/rapid7/metasploit-payloads/commit/fc0079e98a6a4b5f1ce26d8e455a39c3ad34bc24) (especially the Python code) it looks like the intention was the latter.

Agreed. Without bothering to do any tests, it appears that the intention was to perform addition, in which case the second example is correct. That is `$start_id`, with `$`.

File: php/meterpreter/meterpreter.php [hunk 2]
```diff
@@ -512,8 +512,10 @@ function core_enumextcmd($req, &$pkt) {
 
     global $id2f;
 
-    $id_start = packet_get_tlv($req, TLV_TYPE_UINT)['value'];
-    $id_end = packet_get_tlv($req, TLV_TYPE_LENGTH)['value'] + id_start;
+    $id_start_array = packet_get_tlv($req, TLV_TYPE_UINT);
+    $id_start = $id_start_array['value'];
+    $id_end_array = packet_get_tlv($req, TLV_TYPE_LENGTH);
+    $id_end = $id_end_array['value'] + $id_start;
```
Comment (OJ) [inline php/meterpreter/meterpreter.php:518]: This missing `$` was defo picked up in a commit that seems to be lost in the rebase. Sorry! Thank you for fixing that.

Clearly I'm hopeless and have managed to get bitten by the "earlier PHP doesn't index rvalues" issue.

**Comment by OJ** [comment]
Thanks @justinsteven that works at my end. I appreciate you fixing up my mess!
